// --------------------------------------------------------------------------
// 
//                               █▀▀█ ░█─── ▀█▀ ░█▀▀▀█
//                              ░█▄▄█ ░█─── ░█─ ─▀▀▀▄▄
//                              ░█─░█ ░█▄▄█ ▄█▄ ░█▄▄▄█
// 
//  --------------------------------------------------------------------------
//  File:   AutoGeneratedAttribute.cs
// 
//  Author: Pablo Perdomo Falcón
//  Web:    https://www.pabllopf.dev/
// 
//  Copyright (c) 2021 GNU General Public License v3.0
// 
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
// 
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
// 
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
// 
//  --------------------------------------------------------------------------

using System;

namespace Alis.Core.Audio.Core.Native
{
    /// <summary>
    ///     Indicates that this function is generated automatically by a tool.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, Inherited = false)]
    public sealed class AutoGeneratedAttribute : Attribute
    {
        /// <summary>
        ///     Gets or sets the category of this OpenGL function.
        /// </summary>
        public string Category { get; set; }

        /// <summary>
        ///     Gets or sets the entry point of the OpenGL function.
        /// </summary>
        public string EntryPoint { get; set; }

        /// <summary>
        ///     Gets or sets the version of this OpenGL function.
        /// </summary>
        public string Version { get; set; }

        /// <summary>
        ///     Gets or sets the overloader that generated this function.
        /// </summary>
        public string Source { get; set; }
    }
}