//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alis.Core.Audio.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NativeAudio {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NativeAudio() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Alis.Core.Audio.Properties.NativeAudio", typeof(NativeAudio).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] debian_arm64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("debian_arm64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] debian_x64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("debian_x64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_arm64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_x64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("osx_x64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] win_x64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("win_x64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] win_x64_openal32 {
            get {
                object obj = ResourceManager.GetObject("win_x64_openal32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] win_x86_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("win_x86_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] win_x86_openal32 {
            get {
                object obj = ResourceManager.GetObject("win_x86_openal32", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
