//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alis.Core.Audio.Properties {
    using System;
    
    
    /// <summary>
    /// The native audio class
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NativeAudio {
        
        /// <summary>
        /// The resource man
        /// </summary>
        private static System.Resources.ResourceManager resourceMan;
        
        /// <summary>
        /// The resource culture
        /// </summary>
        private static System.Globalization.CultureInfo resourceCulture;
        
        /// <summary>
        /// Initializes a new instance of the <see cref="NativeAudio"/> class
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NativeAudio() {
        }
        
        /// <summary>
        /// Gets the value of the resource manager
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Alis.Core.Audio.Properties.NativeAudio", typeof(NativeAudio).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        /// Gets or sets the value of the culture
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Gets the value of the alpine x64 csfml audio
        /// </summary>
        internal static byte[] alpine_x64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("alpine_x64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the debian arm64 csfml audio
        /// </summary>
        internal static byte[] debian_arm64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("debian_arm64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the debian x64 csfml audio
        /// </summary>
        internal static byte[] debian_x64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("debian_x64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the fedora x64 csfml audio
        /// </summary>
        internal static byte[] fedora_x64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("fedora_x64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx arm64 csfml audio
        /// </summary>
        internal static byte[] osx_arm64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx x64 csfml audio
        /// </summary>
        internal static byte[] osx_x64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("osx_x64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the win x64 csfml audio
        /// </summary>
        internal static byte[] win_x64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("win_x64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the win x86 csfml audio
        /// </summary>
        internal static byte[] win_x86_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("win_x86_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
