# Add 'repo' label to any root file changes
repo:
- '*'

# Add '@domain/core' label to any change within the 'core' package
#@domain/core:
#- package/core/*
#- package/core/**/*

# Add 'test' label to any change to *.spec.js files within the source dir
test:
- any: ['Unit/**/*.cs', 'Integration/**/*.cs', 'Benchmark/**/*.cs', 'Acceptance/**/*.cs']

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
feature:
- any: ['!Unit/**/*.cs', '!Integration/**/*.cs', '!Benchmark/**/*.cs', '!Acceptance/**/*.cs']

# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
#frontend:
#- any: ['src/**/*.js']
#  all: ['!src/main.js']