// 

using System;

namespace Alis.Core.Systems.Audio.Core.Native
{
    /// <summary>
    ///     Indicates that this function is generated automatically by a tool.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, Inherited = false)]
    public sealed class AutoGeneratedAttribute : Attribute
    {
        /// <summary>
        ///     Gets or sets the category of this OpenGL function.
        /// </summary>
        public string Category { get; set; }

        /// <summary>
        ///     Gets or sets the entry point of the OpenGL function.
        /// </summary>
        public string EntryPoint { get; set; }

        /// <summary>
        ///     Gets or sets the version of this OpenGL function.
        /// </summary>
        public string Version { get; set; }

        /// <summary>
        ///     Gets or sets the overloader that generated this function.
        /// </summary>
        public string Source { get; set; }
    }
}