//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alis.Core.Graphic.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NativeGraphic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NativeGraphic() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alis.Core.Graphic.Properties.NativeGraphic", typeof(NativeGraphic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] alpine_x64_cimgui {
            get {
                object obj = ResourceManager.GetObject("alpine-x64_cimgui", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] alpine_x64_csfml_graphics {
            get {
                object obj = ResourceManager.GetObject("alpine-x64_csfml-graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] alpine_x64_csfml_system {
            get {
                object obj = ResourceManager.GetObject("alpine-x64_csfml-system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] alpine_x64_csfml_window {
            get {
                object obj = ResourceManager.GetObject("alpine-x64_csfml-window", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] debian_arm64_cimgui {
            get {
                object obj = ResourceManager.GetObject("debian-arm64_cimgui", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] debian_arm64_csfml_graphics {
            get {
                object obj = ResourceManager.GetObject("debian-arm64_csfml-graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] debian_arm64_csfml_system {
            get {
                object obj = ResourceManager.GetObject("debian-arm64_csfml-system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] debian_arm64_csfml_window {
            get {
                object obj = ResourceManager.GetObject("debian-arm64_csfml-window", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] debian_x64_cimgui {
            get {
                object obj = ResourceManager.GetObject("debian-x64_cimgui", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] debian_x64_cimgui1 {
            get {
                object obj = ResourceManager.GetObject("debian-x64_cimgui1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] debian_x64_csfml_graphics {
            get {
                object obj = ResourceManager.GetObject("debian-x64_csfml-graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] debian_x64_csfml_graphics1 {
            get {
                object obj = ResourceManager.GetObject("debian-x64_csfml-graphics1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] debian_x64_csfml_system {
            get {
                object obj = ResourceManager.GetObject("debian-x64_csfml-system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] debian_x64_csfml_system1 {
            get {
                object obj = ResourceManager.GetObject("debian-x64_csfml-system1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] debian_x64_csfml_window {
            get {
                object obj = ResourceManager.GetObject("debian-x64_csfml-window", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] debian_x64_csfml_window1 {
            get {
                object obj = ResourceManager.GetObject("debian-x64_csfml-window1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] fedora_x64_cimgui {
            get {
                object obj = ResourceManager.GetObject("fedora-x64_cimgui", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] fedora_x64_csfml_graphics {
            get {
                object obj = ResourceManager.GetObject("fedora-x64_csfml-graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] fedora_x64_csfml_system {
            get {
                object obj = ResourceManager.GetObject("fedora-x64_csfml-system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] fedora_x64_csfml_window {
            get {
                object obj = ResourceManager.GetObject("fedora-x64_csfml-window", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_arm64_cimgui {
            get {
                object obj = ResourceManager.GetObject("osx-arm64_cimgui", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_arm64_csfml_graphics {
            get {
                object obj = ResourceManager.GetObject("osx-arm64_csfml-graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_arm64_csfml_system {
            get {
                object obj = ResourceManager.GetObject("osx-arm64_csfml-system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_arm64_csfml_window {
            get {
                object obj = ResourceManager.GetObject("osx-arm64_csfml-window", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_arm64_sdl2 {
            get {
                object obj = ResourceManager.GetObject("osx-arm64_sdl2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_arm64_sdl2_image {
            get {
                object obj = ResourceManager.GetObject("osx-arm64_sdl2_image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_arm64_sdl2_mixer {
            get {
                object obj = ResourceManager.GetObject("osx-arm64_sdl2_mixer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_arm64_sdl2_ttf {
            get {
                object obj = ResourceManager.GetObject("osx-arm64_sdl2_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_x64_cimgui {
            get {
                object obj = ResourceManager.GetObject("osx-x64_cimgui", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_x64_csfml_graphics {
            get {
                object obj = ResourceManager.GetObject("osx-x64_csfml-graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_x64_csfml_system {
            get {
                object obj = ResourceManager.GetObject("osx-x64_csfml-system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_x64_csfml_window {
            get {
                object obj = ResourceManager.GetObject("osx-x64_csfml-window", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_x64_sdl2 {
            get {
                object obj = ResourceManager.GetObject("osx-x64_sdl2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_x64_sdl2_image {
            get {
                object obj = ResourceManager.GetObject("osx-x64_sdl2_image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_x64_sdl2_mixer {
            get {
                object obj = ResourceManager.GetObject("osx-x64_sdl2_mixer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] osx_x64_sdl2_ttf {
            get {
                object obj = ResourceManager.GetObject("osx-x64_sdl2_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_arm64_cimgui {
            get {
                object obj = ResourceManager.GetObject("win-arm64_cimgui", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_arm64_csfml_graphics {
            get {
                object obj = ResourceManager.GetObject("win-arm64_csfml-graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_arm64_csfml_system {
            get {
                object obj = ResourceManager.GetObject("win-arm64_csfml-system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_arm64_csfml_window {
            get {
                object obj = ResourceManager.GetObject("win-arm64_csfml-window", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_arm64_sdl2 {
            get {
                object obj = ResourceManager.GetObject("win-arm64_sdl2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_arm64_sdl2_image {
            get {
                object obj = ResourceManager.GetObject("win-arm64_sdl2_image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_arm64_sdl2_mixer {
            get {
                object obj = ResourceManager.GetObject("win-arm64_sdl2_mixer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_arm64_sdl2_ttf {
            get {
                object obj = ResourceManager.GetObject("win-arm64_sdl2_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x64_cimgui {
            get {
                object obj = ResourceManager.GetObject("win-x64_cimgui", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x64_csfml_graphics {
            get {
                object obj = ResourceManager.GetObject("win-x64_csfml-graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x64_csfml_system {
            get {
                object obj = ResourceManager.GetObject("win-x64_csfml-system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x64_csfml_window {
            get {
                object obj = ResourceManager.GetObject("win-x64_csfml-window", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x64_sdl2 {
            get {
                object obj = ResourceManager.GetObject("win-x64_sdl2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x64_sdl2_image {
            get {
                object obj = ResourceManager.GetObject("win-x64_sdl2_image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x64_sdl2_mixer {
            get {
                object obj = ResourceManager.GetObject("win-x64_sdl2_mixer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x64_sdl2_ttf {
            get {
                object obj = ResourceManager.GetObject("win-x64_sdl2_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x86_cimgui {
            get {
                object obj = ResourceManager.GetObject("win-x86_cimgui", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x86_csfml_graphics {
            get {
                object obj = ResourceManager.GetObject("win-x86_csfml-graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x86_csfml_system {
            get {
                object obj = ResourceManager.GetObject("win-x86_csfml-system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x86_csfml_window {
            get {
                object obj = ResourceManager.GetObject("win-x86_csfml-window", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x86_sdl2 {
            get {
                object obj = ResourceManager.GetObject("win-x86_sdl2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x86_sdl2_image {
            get {
                object obj = ResourceManager.GetObject("win-x86_sdl2_image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x86_sdl2_mixer {
            get {
                object obj = ResourceManager.GetObject("win-x86_sdl2_mixer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] win_x86_sdl2_ttf {
            get {
                object obj = ResourceManager.GetObject("win-x86_sdl2_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
