//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alis.Core.Graphic.Properties {
    /// <summary>
    /// The resources class
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        /// <summary>
        /// The resource man
        /// </summary>
        private static System.Resources.ResourceManager resourceMan;
        
        /// <summary>
        /// The resource culture
        /// </summary>
        private static System.Globalization.CultureInfo resourceCulture;
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Resources"/> class
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Gets the value of the resource manager
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Alis.Core.Graphic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        /// Gets or sets the value of the culture
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Gets the value of the osx arm64 libcsfml graphics 2 5 1
        /// </summary>
        internal static byte[] osx_arm64_libcsfml_graphics_2_5_1 {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_libcsfml_graphics_2_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx arm64 libcsfml system 2 5 1
        /// </summary>
        internal static byte[] osx_arm64_libcsfml_system_2_5_1 {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_libcsfml_system_2_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx arm64 libcsfml window 2 5 1
        /// </summary>
        internal static byte[] osx_arm64_libcsfml_window_2_5_1 {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_libcsfml_window_2_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx x64 libcsfml graphics 2 5 1
        /// </summary>
        internal static byte[] osx_x64_libcsfml_graphics_2_5_1 {
            get {
                object obj = ResourceManager.GetObject("osx_x64_libcsfml_graphics_2_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx x64 libcsfml system 2 5 1
        /// </summary>
        internal static byte[] osx_x64_libcsfml_system_2_5_1 {
            get {
                object obj = ResourceManager.GetObject("osx_x64_libcsfml_system_2_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx x64 libcsfml window 2 5 1
        /// </summary>
        internal static byte[] osx_x64_libcsfml_window_2_5_1 {
            get {
                object obj = ResourceManager.GetObject("osx_x64_libcsfml_window_2_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
