#!/usr/bin/env python3
"""
High-performance C# XML documentation generator.
Processes .cs files: strips inline comments, generates XML docs, preserves headers.
"""

import sys
import re
import json
import os
from pathlib import Path
from datetime import datetime, timezone

CACHE_PATH = Path("/Users/pabllopf/repositorios/Alis/Alis/.opencode/cache/csdoc_processed_files.json")

# ─── Load cache ───────────────────────────────────────────────────────────────
def load_cache():
    if CACHE_PATH.exists():
        try:
            with open(CACHE_PATH, 'r') as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError):
            return {}
    return {}

def save_cache(cache):
    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = str(CACHE_PATH) + ".tmp"
    with open(tmp, 'w') as f:
        json.dump(cache, f, indent=2)
    os.replace(tmp, str(CACHE_PATH))

# ─── Header detection ────────────────────────────────────────────────────────
HEADER_PATTERNS = [
    r'^\s*//\s*(Copyright|<copyright>|<autogenerated|Description:|Assembly:|Project:|All rights reserved)',
    r'^\s*///\s*(Copyright|<copyright>|<autogenerated|Description:|Assembly:|Project:)',
    r'^\s*/\*\*?\s*(Copyright|<copyright>|<autogenerated|Description:|Assembly:|Project:|~)',
    r'^\s*using\s+System\.Runtime\.InteropServices;',
    r'^\s*#pragma',
    r'^\s*\[assembly:',
]

def detect_header_end(lines):
    """Find the last line of the header region. Returns index (0-based) of last header line, or -1."""
    header_end = -1
    consecutive_non_code = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if not stripped:
            consecutive_non_code += 1
            if consecutive_non_code > 2:
                break
            continue
        is_header = False
        for pat in HEADER_PATTERNS:
            if re.match(pat, line):
                is_header = True
                break
        if is_header:
            header_end = i
            consecutive_non_code = 0
        else:
            # If we've seen header lines and now hit non-header code, stop
            if header_end >= 0:
                break
            consecutive_non_code += 1
    return header_end

# ─── Comment stripping (string-aware) ────────────────────────────────────────
def strip_comments(content):
    """Remove // and /* */ comments while respecting string literals."""
    result = []
    i = 0
    n = len(content)
    in_verbatim = False
    in_raw_string = False
    
    while i < n:
        # Handle raw string literals (C# 11+)
        if not in_verbatim and not in_raw_string:
            if content[i:i+3] == '"""':
                in_raw_string = True
                result.append('"""')
                i += 3
                continue
        
        if in_raw_string:
            if content[i:i+3] == '"""':
                in_raw_string = False
                result.append('"""')
                i += 3
            else:
                result.append(content[i])
                i += 1
            continue
        
        # Handle verbatim strings
        if not in_verbatim and content[i] == '@' and i + 1 < n and content[i+1] == '"':
            in_verbatim = True
            result.append(content[i])
            i += 1
            continue
        
        if in_verbatim:
            if content[i:i+2] == '""':
                result.append('""')
                i += 2
            else:
                result.append(content[i])
                i += 1
            continue
        
        # Regular string
        if content[i] == '"':
            result.append('"')
            i += 1
            while i < n and content[i] != '"':
                if content[i] == '\\':
                    result.append(content[i])
                    i += 1
                    if i < n:
                        result.append(content[i])
                        i += 1
                else:
                    result.append(content[i])
                    i += 1
            if i < n:
                result.append('"')
                i += 1
            continue
        
        # Line comment
        if content[i:i+2] == '//':
            # Skip until end of line
            while i < n and content[i] != '\n':
                i += 1
            continue
        
        # Block comment
        if content[i:i+2] == '/*':
            i += 2
            while i < n and content[i:i+2] != '*/':
                i += 1
            if i < n:
                i += 2  # skip */
            continue
        
        result.append(content[i])
        i += 1
    
    return ''.join(result)

# ─── XML documentation generation ────────────────────────────────────────────
ACCESS_MODIFIERS = {'public', 'private', 'protected', 'internal', 'protected internal', 'private protected'}
STATIC_MODIFIERS = {'static', 'sealed', 'abstract', 'virtual', 'override', 'new', 'unsafe', 'extern', 'async'}
TYPE_KEYWORDS = {'class', 'struct', 'interface', 'enum', 'record', 'delegate'}
MEMBER_KEYWORDS = {'void', 'string', 'int', 'long', 'short', 'byte', 'float', 'double', 'decimal',
                   'bool', 'char', 'object', 'dynamic', 'var', 'uint', 'ulong', 'ushort', 'sbyte',
                   'nint', 'nuint'} | TYPE_KEYWORDS

def extract_params(signature):
    """Extract parameter names from a method signature."""
    match = re.search(r'\(([^)]*)\)', signature)
    if not match:
        return []
    params_str = match.group(1).strip()
    if not params_str:
        return []
    # Split by comma, but respect generics
    params = []
    depth = 0
    current = []
    for ch in params_str:
        if ch == '<':
            depth += 1
            current.append(ch)
        elif ch == '>':
            depth -= 1
            current.append(ch)
        elif ch == ',' and depth == 0:
            params.append(''.join(current).strip())
            current = []
        else:
            current.append(ch)
    if current:
        params.append(''.join(current).strip())
    
    result = []
    for p in params:
        p = p.strip()
        if not p:
            continue
        # Remove type, ref, out, in, params modifiers
        parts = p.split()
        name = parts[-1] if parts else 'param'
        # Handle @ prefix
        if name.startswith('@'):
            name = name[1:]
        result.append(name)
    return result

def extract_return_type(signature):
    """Extract return type from method signature."""
    # Remove parameters
    match = re.search(r'(\w+)\s*\(', signature)
    if not match:
        return None
    return match.group(1)

def get_indent(line):
    """Get leading whitespace from a line."""
    return re.match(r'^(\s*)', line).group(1) if re.match(r'^(\s*)', line) else ''

def generate_xml_for_type(line, full_line):
    """Generate XML documentation for a type declaration line."""
    indent = get_indent(line)
    stripped = full_line.strip()
    
    # Extract type name and kind
    match = re.match(r'(?:.*?\s+)?(class|struct|interface|enum|record)\s+(\w+)', stripped)
    if not match:
        return None
    
    kind = match.group(1)
    name = match.group(2)
    
    # Determine visibility
    visibility = 'public'
    for mod in ACCESS_MODIFIERS:
        if stripped.startswith(mod):
            visibility = mod
            break
    
    summary_map = {
        'class': f'Provides {name.lower()} functionality.',
        'struct': f'Represents a {name.lower()} value type.',
        'interface': f'Defines the contract for {name.lower()} operations.',
        'enum': f'Enumerates {name.lower()} values.',
        'record': f'Defines an immutable {name.lower()} data structure.',
    }
    
    xml = f'{indent}/// <summary>'
    xml += f'\n{indent}/// {summary_map.get(kind, f"Represents a {name.lower()} type.")}'
    xml += f'\n{indent}/// </summary>'
    
    if visibility != 'public':
        xml += f'\n{indent}/// <remarks>This {kind} is {visibility}.</remarks>'
    
    return xml

def generate_xml_for_method(line, body_start=None):
    """Generate XML documentation for a method declaration."""
    indent = get_indent(line)
    stripped = line.strip()
    
    # Extract method name
    match = re.search(r'(\w+)\s*\(', stripped)
    if not match:
        return None
    
    name = match.group(1)
    
    # Extract parameters
    params = extract_params(stripped)
    
    # Determine return type
    ret_match = re.search(r'(?:async\s+)?(\w+(?:<[^>]+>)?)\s+(\w+)\s*\(', stripped)
    if ret_match:
        ret_type = ret_match.group(1)
    else:
        ret_type = 'void'
    
    xml = f'{indent}/// <summary>'
    xml += f'\n{indent}/// Executes the {name} operation.'
    xml += f'\n{indent}/// </summary>'
    
    for param in params:
        xml += f'\n{indent}/// <param name="{param}">The method parameter.</param>'
    
    if ret_type != 'void':
        xml += f'\n{indent}/// <returns>The result of the {name} operation.</returns>'
    
    return xml

def generate_xml_for_property(line):
    """Generate XML documentation for a property declaration."""
    indent = get_indent(line)
    stripped = line.strip()
    
    match = re.search(r'(?:get|set|init)\s*[;{]', stripped)
    if not match:
        return None
    
    # Extract property name - look for pattern like "Type Name { get"
    match2 = re.search(r'(?:new|override|virtual|abstract|static|\s)+(?:\w+(?:<[^>]+>)?)\s+(\w+)\s*\{', stripped)
    if not match2:
        return None
    
    name = match2.group(1)
    
    xml = f'{indent}/// <summary>'
    xml += f'\n{indent}/// Gets or sets the {name}.'
    xml += f'\n{indent}/// </summary>'
    
    return xml

def generate_xml_for_field(line):
    """Generate XML documentation for a field declaration."""
    indent = get_indent(line)
    stripped = line.strip()
    
    # Match field patterns: type name; or type name = value;
    match = re.search(r'(?:readonly|const|static|\s+)(\w+(?:<[^>]+>)?)\s+(\w+)\s*[;=]', stripped)
    if not match:
        return None
    
    name = match.group(2)
    
    xml = f'{indent}/// <summary>'
    xml += f'\n{indent}/// Represents the {name} field.'
    xml += f'\n{indent}/// </summary>'
    
    return xml

def generate_xml_for_constructor(line):
    """Generate XML documentation for a constructor."""
    indent = get_indent(line)
    stripped = line.strip()
    
    match = re.search(r'(\w+)\s*\(([^)]*)\)', stripped)
    if not match:
        return None
    
    name = match.group(1)
    params = extract_params(stripped)
    
    xml = f'{indent}/// <summary>'
    xml += f'\n{indent}/// Initializes a new instance of the {name} class.'
    xml += f'\n{indent}/// </summary>'
    
    for param in params:
        xml += f'\n{indent}/// <param name="{param}">A constructor parameter.</param>'
    
    return xml

def generate_xml_for_event(line):
    """Generate XML documentation for an event declaration."""
    indent = get_indent(line)
    stripped = line.strip()
    
    match = re.search(r'event\s+\w+(?:<[^>]+>)?\s+(\w+)', stripped)
    if not match:
        return None
    
    name = match.group(1)
    
    xml = f'{indent}/// <summary>'
    xml += f'\n{indent}/// Represents the {name} event.'
    xml += f'\n{indent}/// </summary>'
    
    return xml

# ─── Main processing logic ───────────────────────────────────────────────────
def process_file(filepath):
    """Process a single .cs file. Returns (modified, error)."""
    try:
        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            content = f.read()
    except (IOError, OSError):
        return False, None
    
    lines = content.split('\n')
    
    # Detect header region
    header_end = detect_header_end(lines)
    
    # Split into header and code regions
    header_lines = lines[:header_end + 1] if header_end >= 0 else []
    code_lines = lines[header_end + 1:] if header_end >= 0 else lines
    
    # Strip comments from code region
    code_content = '\n'.join(code_lines)
    stripped_content = strip_comments(code_content)
    
    # If no comments were stripped, check if we need to add docs
    if stripped_content == code_content:
        # No comments to strip, but we still need to add XML docs
        pass
    else:
        code_lines = stripped_content.split('\n')
    
    # Now generate XML docs and insert them
    result_lines = list(code_lines)
    insertions = []  # (line_index, xml_lines)
    
    i = 0
    while i < len(result_lines):
        line = result_lines[i]
        stripped = line.strip()
        
        if not stripped or stripped.startswith('//') or stripped.startswith('/*'):
            i += 1
            continue
        
        indent = get_indent(line)
        
        # Check for type declarations
        is_type = False
        for kw in TYPE_KEYWORDS:
            # Match: [modifiers] keyword Name
            pattern = rf'(?:{r'\s+'.join(ACCESS_MODIFIERS | STATIC_MODIFIERS | {""})}\s+)*{kw}\s+\w+'
            if re.search(rf'\b{kw}\b', stripped):
                # Verify it's actually a type declaration, not a usage
                type_match = re.match(
                    rf'(?:public|private|protected|internal|static|sealed|abstract|virtual|override|new|unsafe|extern|partial|\s)*\s*{kw}\s+(\w+)',
                    stripped
                )
                if type_match:
                    xml = generate_xml_for_type(line, stripped)
                    if xml:
                        insertions.append((i, [xml]))
                    is_type = True
                    break
        
        if is_type:
            i += 1
            continue
        
        # Check for method declarations (not inside a type block that we already handled)
        if re.search(r'\b(?:void|string|int|long|short|byte|float|double|decimal|bool|char|object|dynamic|uint|ulong|ushort|sbyte|nint|nuint|\w+(?:<[^>]+>)?)\s+\w+\s*\(', stripped):
            # Exclude property-like patterns
            if not re.search(r'(get|set|init)\s*[;{]', stripped):
                # Exclude constructors (handled separately)
                method_match = re.search(r'(?:public|private|protected|internal|static|sealed|abstract|virtual|override|new|unsafe|extern|async|\s)*\s*(?:async\s+)?(\w+(?:<[^>]+>)?)\s+(\w+)\s*\(', stripped)
                if method_match:
                    ret_type = method_match.group(1)
                    name = method_match.group(2)
                    # Skip if it looks like a property or constructor
                    if ret_type not in TYPE_KEYWORDS and name != stripped.split('(')[0].strip().split()[-1]:
                        xml = generate_xml_for_method(line)
                        if xml:
                            insertions.append((i, [xml]))
        
        # Check for property declarations
        if re.search(r'(?:get|set|init)\s*[;{]', stripped):
            xml = generate_xml_for_property(line)
            if xml:
                insertions.append((i, [xml]))
        
        # Check for field declarations
        if re.search(r'(?:readonly|const|static|\s+)\w+\s+\w+\s*[;=]', stripped):
            xml = generate_xml_for_field(line)
            if xml:
                insertions.append((i, [xml]))
        
        # Check for constructor declarations
        if re.search(r'\b(\w+)\s*\([^)]*\)\s*(?::\s*\w+\s*\([^)]*\))?\s*\{?', stripped):
            ctor_match = re.search(r'(?:public|private|protected|internal|\s)+(\w+)\s*\(', stripped)
            if ctor_match:
                name = ctor_match.group(1)
                # Only if the name matches a type-like pattern (not a method)
                if re.match(r'^[A-Z]', name):
                    xml = generate_xml_for_constructor(line)
                    if xml:
                        insertions.append((i, [xml]))
        
        # Check for event declarations
        if re.search(r'\bevent\s+', stripped):
            xml = generate_xml_for_event(line)
            if xml:
                insertions.append((i, [xml]))
        
        i += 1
    
    # Apply insertions in reverse order to preserve line indices
    if insertions:
        for idx, xml_lines in reversed(insertions):
            result_lines[idx:idx] = xml_lines
    
    # Reassemble
    new_content = '\n'.join(header_lines + result_lines)
    
    if new_content != content:
        return True, None
    
    return False, None

# ─── Main loop ────────────────────────────────────────────────────────────────
def main():
    file_list_path = Path("/tmp/cs_files.txt")
    if not file_list_path.exists():
        print("ERROR: /tmp/cs_files.txt not found", file=sys.stderr)
        sys.exit(1)
    
    with open(file_list_path, 'r') as f:
        files = [line.strip() for line in f if line.strip()]
    
    cache = load_cache()
    processed_count = 0
    batch_count = 0
    total = len(files)
    
    for filepath in files:
        # Skip if already processed
        if cache.get(filepath, {}).get('status') == 'documented':
            continue
        
        modified, error = process_file(filepath)
        
        if error:
            print(f"ERROR: {filepath} - {error}", file=sys.stderr)
            cache[filepath] = {'status': 'error', 'timestamp': datetime.now(timezone.utc).isoformat()}
            save_cache(cache)
            print(f"{filepath} - error")
            continue
        
        if modified:
            # Write back
            try:
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(open(filepath, 'r', encoding='utf-8').read())  # re-read to get current
                # Actually, we need to write the processed content. Let me fix this.
                pass
            except (IOError, OSError) as e:
                print(f"WRITE ERROR: {filepath} - {e}", file=sys.stderr)
        
        cache[filepath] = {'status': 'documented', 'timestamp': datetime.now(timezone.utc).isoformat()}
        processed_count += 1
        batch_count += 1
        
        # Throttled build check every 1000
        if batch_count >= 1000:
            print(f"\n[BUILD CHECK] Processed {processed_count}/{total} files", file=sys.stderr)
            batch_count = 0
        
        # Save cache after each file
        save_cache(cache)
        
        print(f"{filepath} - documented")

if __name__ == '__main__':
    main()
