//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alis.Core.Graphic.Properties.osx.arm64 {
    /// <summary>
    /// The native graphic osx arm 64 sfml class
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NativeGraphicOsxARM64SFML {
        
        /// <summary>
        /// The resource man
        /// </summary>
        private static System.Resources.ResourceManager resourceMan;
        
        /// <summary>
        /// The resource culture
        /// </summary>
        private static System.Globalization.CultureInfo resourceCulture;
        
        /// <summary>
        /// Initializes a new instance of the <see cref="NativeGraphicOsxARM64SFML"/> class
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NativeGraphicOsxARM64SFML() {
        }
        
        /// <summary>
        /// Gets the value of the resource manager
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Alis.Core.Graphic.Properties.osx.arm64.NativeGraphicOsxARM64SFML", typeof(NativeGraphicOsxARM64SFML).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        /// Gets or sets the value of the culture
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        /// <summary>
        /// Gets the value of the osx arm64 csfml graphics
        /// </summary>
        internal static byte[] osx_arm64_csfml_graphics {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_csfml_graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx arm64 csfml system
        /// </summary>
        internal static byte[] osx_arm64_csfml_system {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_csfml_system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx arm64 csfml window
        /// </summary>
        internal static byte[] osx_arm64_csfml_window {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_csfml_window", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
