//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alis.Core.Graphic.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NativeGraphicOsxARM64 {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NativeGraphicOsxARM64() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Alis.Core.Graphic.Properties.osx.arm64.NativeGraphicOsxARM64", typeof(NativeGraphicOsxARM64).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] osx_arm64_cimgui {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_cimgui", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_arm64_csfml_graphics {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_csfml_graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_arm64_csfml_system {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_csfml_system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_arm64_csfml_window {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_csfml_window", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_arm64_sdl2 {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_sdl2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_arm64_sdl2_image {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_sdl2_image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_arm64_sdl2_ttf {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_sdl2_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_x64_cimgui {
            get {
                object obj = ResourceManager.GetObject("osx_x64_cimgui", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_x64_csfml_graphics {
            get {
                object obj = ResourceManager.GetObject("osx_x64_csfml_graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_x64_csfml_system {
            get {
                object obj = ResourceManager.GetObject("osx_x64_csfml_system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_x64_csfml_window {
            get {
                object obj = ResourceManager.GetObject("osx_x64_csfml_window", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_x64_sdl2 {
            get {
                object obj = ResourceManager.GetObject("osx_x64_sdl2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_x64_sdl2_image {
            get {
                object obj = ResourceManager.GetObject("osx_x64_sdl2_image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_x64_sdl2_ttf {
            get {
                object obj = ResourceManager.GetObject("osx_x64_sdl2_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
