#!/usr/bin/env python3
"""
High-performance C# XML documentation generator.
Processes .cs files: strips inline comments, generates XML docs, preserves headers.
"""

import sys
import re
import json
import os
from pathlib import Path
from datetime import datetime, timezone

CACHE_PATH = Path("/Users/pabllopf/repositorios/Alis/Alis/.opencode/cache/csdoc_processed_files.json")

# ─── Load cache ───────────────────────────────────────────────────────────────
def load_cache():
    if CACHE_PATH.exists():
        try:
            with open(CACHE_PATH, 'r') as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError):
            return {}
    return {}

def save_cache(cache):
    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = str(CACHE_PATH) + ".tmp"
    with open(tmp, 'w') as f:
        json.dump(cache, f, indent=2)
    os.replace(tmp, str(CACHE_PATH))

# ─── Header detection ────────────────────────────────────────────────────────
HEADER_PATTERNS = [
    r'^\s*//\s*(Copyright|<copyright>|<autogenerated|Description:|Assembly:|Project:|All rights reserved|Licensed)',
    r'^\s*///\s*(Copyright|<copyright>|<autogenerated|Description:|Assembly:|Project:|Licensed)',
    r'^\s*/\*\*?\s*(Copyright|<copyright>|<autogenerated|Description:|Assembly:|Project:|~|\*)',
    r'^\s*using\s+System\.Runtime\.InteropServices;',
    r'^\s*#pragma',
    r'^\s*\[assembly:',
]

def detect_header_end(lines):
    """Find the last line of the header region."""
    header_end = -1
    consecutive_non_code = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if not stripped:
            consecutive_non_code += 1
            if consecutive_non_code > 2:
                break
            continue
        is_header = False
        for pat in HEADER_PATTERNS:
            if re.match(pat, line):
                is_header = True
                break
        if is_header:
            header_end = i
            consecutive_non_code = 0
        else:
            if header_end >= 0:
                break
            consecutive_non_code += 1
    return header_end

# ─── Comment stripping (string-aware) ────────────────────────────────────────
def strip_comments(content):
    """Remove // and /* */ comments while respecting string literals."""
    result = []
    i = 0
    n = len(content)
    in_verbatim = False
    in_raw_string = False
    
    while i < n:
        # Handle raw string literals (C# 11+)
        if not in_verbatim and not in_raw_string:
            if content[i:i+3] == '"""':
                in_raw_string = True
                result.append('"""')
                i += 3
                continue
        
        if in_raw_string:
            if content[i:i+3] == '"""':
                in_raw_string = False
                result.append('"""')
                i += 3
            else:
                result.append(content[i])
                i += 1
            continue
        
        # Handle verbatim strings
        if not in_verbatim and content[i] == '@' and i + 1 < n and content[i+1] == '"':
            in_verbatim = True
            result.append(content[i])
            i += 1
            continue
        
        if in_verbatim:
            if content[i:i+2] == '""':
                result.append('""')
                i += 2
            else:
                result.append(content[i])
                i += 1
            continue
        
        # Regular string
        if content[i] == '"':
            result.append('"')
            i += 1
            while i < n and content[i] != '"':
                if content[i] == '\\':
                    result.append(content[i])
                    i += 1
                    if i < n:
                        result.append(content[i])
                        i += 1
                else:
                    result.append(content[i])
                    i += 1
            if i < n:
                result.append('"')
                i += 1
            continue
        
        # Line comment
        if content[i:i+2] == '//':
            while i < n and content[i] != '\n':
                i += 1
            continue
        
        # Block comment
        if content[i:i+2] == '/*':
            i += 2
            while i < n and content[i:i+2] != '*/':
                i += 1
            if i < n:
                i += 2
            continue
        
        result.append(content[i])
        i += 1
    
    return ''.join(result)

# ─── XML documentation generation ────────────────────────────────────────────
def extract_params(signature):
    """Extract parameter names from a method signature."""
    match = re.search(r'\(([^)]*)\)', signature)
    if not match:
        return []
    params_str = match.group(1).strip()
    if not params_str:
        return []
    params = []
    depth = 0
    current = []
    for ch in params_str:
        if ch == '<':
            depth += 1
            current.append(ch)
        elif ch == '>':
            depth -= 1
            current.append(ch)
        elif ch == ',' and depth == 0:
            params.append(''.join(current).strip())
            current = []
        else:
            current.append(ch)
    if current:
        params.append(''.join(current).strip())
    
    result = []
    for p in params:
        p = p.strip()
        if not p:
            continue
        parts = p.split()
        name = parts[-1] if parts else 'param'
        if name.startswith('@'):
            name = name[1:]
        result.append(name)
    return result

def get_indent(line):
    """Get leading whitespace from a line."""
    m = re.match(r'^(\s*)', line)
    return m.group(1) if m else ''

def is_type_declaration(stripped):
    """Check if a line declares a type (class, struct, interface, enum, record)."""
    # Match patterns like: public class Foo, internal sealed interface IFoo, etc.
    pattern = r'(?:public|private|protected|internal|static|sealed|abstract|virtual|override|new|unsafe|extern|partial|\s)*\s*(class|struct|interface|enum|record)\s+(\w+)'
    return re.match(pattern, stripped)

def is_method_declaration(stripped):
    """Check if a line declares a method."""
    # Must have a return type, name, and parentheses
    pattern = r'(?:public|private|protected|internal|static|sealed|abstract|virtual|override|new|unsafe|extern|async|\s)*\s*(?:async\s+)?(?:void|string|int|long|short|byte|float|double|decimal|bool|char|object|dynamic|uint|ulong|ushort|sbyte|nint|nuint|\w+(?:<[^>]+>)?)\s+(\w+)\s*\('
    m = re.match(pattern, stripped)
    if not m:
        return False, None
    name = m.group(1)
    # Exclude constructors (name starts with uppercase and matches surrounding type context)
    # Exclude property accessors
    if re.search(r'(get|set|init)\s*[;{]', stripped):
        return False, None
    # Exclude if it's a type keyword being used as a type
    if name in ('class', 'struct', 'interface', 'enum', 'record'):
        return False, None
    return True, name

def is_property_declaration(stripped):
    """Check if a line declares a property."""
    return bool(re.search(r'(?:get|set|init)\s*[;{]', stripped))

def is_field_declaration(stripped):
    """Check if a line declares a field."""
    return bool(re.search(r'(?:readonly|const|static|\s+)\w+\s+\w+\s*[;=]', stripped))

def is_constructor_declaration(stripped):
    """Check if a line declares a constructor."""
    m = re.match(r'(?:public|private|protected|internal|\s)+([A-Z]\w*)\s*\(', stripped)
    if m:
        return True, m.group(1)
    return False, None

def is_event_declaration(stripped):
    """Check if a line declares an event."""
    return bool(re.search(r'\bevent\s+', stripped))

def generate_xml_for_type(stripped, indent):
    """Generate XML documentation for a type declaration."""
    m = re.match(r'(?:public|private|protected|internal|static|sealed|abstract|virtual|override|new|unsafe|extern|partial|\s)*\s*(class|struct|interface|enum|record)\s+(\w+)', stripped)
    if not m:
        return None
    
    kind = m.group(1)
    name = m.group(2)
    
    visibility = 'public'
    for mod in ('public', 'private', 'protected', 'internal'):
        if stripped.lstrip().startswith(mod):
            visibility = mod
            break
    
    summaries = {
        'class': f'Provides {name.lower()} functionality.',
        'struct': f'Represents a {name.lower()} value type.',
        'interface': f'Defines the contract for {name.lower()} operations.',
        'enum': f'Enumerates {name.lower()} values.',
        'record': f'Defines an immutable {name.lower()} data structure.',
    }
    
    xml = f'{indent}/// <summary>'
    xml += f'\n{indent}/// {summaries.get(kind, f"Represents a {name.lower()} type.")}'
    xml += f'\n{indent}/// </summary>'
    
    if visibility != 'public':
        xml += f'\n{indent}/// <remarks>This {kind} is {visibility}.</remarks>'
    
    return xml

def generate_xml_for_method(stripped, indent):
    """Generate XML documentation for a method declaration."""
    m = re.search(r'(\w+)\s*\(', stripped)
    if not m:
        return None
    
    name = m.group(1)
    params = extract_params(stripped)
    
    ret_match = re.search(r'(?:async\s+)?(?:void|string|int|long|short|byte|float|double|decimal|bool|char|object|dynamic|uint|ulong|ushort|sbyte|nint|nuint|\w+(?:<[^>]+>)?)\s+\w+\s*\(', stripped)
    ret_type = ret_match.group(1).replace('async', '').strip() if ret_match else 'void'
    
    xml = f'{indent}/// <summary>'
    xml += f'\n{indent}/// Executes the {name} operation.'
    xml += f'\n{indent}/// </summary>'
    
    for param in params:
        xml += f'\n{indent}/// <param name="{param}">The method parameter.</param>'
    
    if ret_type != 'void':
        xml += f'\n{indent}/// <returns>The result of the {name} operation.</returns>'
    
    return xml

def generate_xml_for_property(stripped, indent):
    """Generate XML documentation for a property declaration."""
    m = re.search(r'(?:new|override|virtual|abstract|static|\s+)?(?:\w+(?:<[^>]+>)?)\s+(\w+)\s*\{', stripped)
    if not m:
        return None
    
    name = m.group(1)
    
    xml = f'{indent}/// <summary>'
    xml += f'\n{indent}/// Gets or sets the {name}.'
    xml += f'\n{indent}/// </summary>'
    
    return xml

def generate_xml_for_field(stripped, indent):
    """Generate XML documentation for a field declaration."""
    m = re.search(r'(?:readonly|const|static|\s+)(\w+(?:<[^>]+>)?)\s+(\w+)\s*[;=]', stripped)
    if not m:
        return None
    
    name = m.group(2)
    
    xml = f'{indent}/// <summary>'
    xml += f'\n{indent}/// Represents the {name} field.'
    xml += f'\n{indent}/// </summary>'
    
    return xml

def generate_xml_for_constructor(stripped, indent):
    """Generate XML documentation for a constructor."""
    m = re.match(r'(?:public|private|protected|internal|\s)+(\w+)\s*\(([^)]*)\)', stripped)
    if not m:
        return None
    
    name = m.group(1)
    params = extract_params(stripped)
    
    xml = f'{indent}/// <summary>'
    xml += f'\n{indent}/// Initializes a new instance of the {name} class.'
    xml += f'\n{indent}/// </summary>'
    
    for param in params:
        xml += f'\n{indent}/// <param name="{param}">A constructor parameter.</param>'
    
    return xml

def generate_xml_for_event(stripped, indent):
    """Generate XML documentation for an event declaration."""
    m = re.search(r'event\s+\w+(?:<[^>]+>)?\s+(\w+)', stripped)
    if not m:
        return None
    
    name = m.group(1)
    
    xml = f'{indent}/// <summary>'
    xml += f'\n{indent}/// Represents the {name} event.'
    xml += f'\n{indent}/// </summary>'
    
    return xml

# ─── Main processing logic ───────────────────────────────────────────────────
def process_file(filepath):
    """Process a single .cs file. Returns (new_content, was_modified)."""
    try:
        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            content = f.read()
    except (IOError, OSError):
        return None, False
    
    lines = content.split('\n')
    
    # Detect header region
    header_end = detect_header_end(lines)
    
    # Split into header and code regions
    header_lines = lines[:header_end + 1] if header_end >= 0 else []
    code_lines = lines[header_end + 1:] if header_end >= 0 else list(lines)
    
    # Strip comments from code region
    code_content = '\n'.join(code_lines)
    stripped_content = strip_comments(code_content)
    
    if stripped_content != code_content:
        code_lines = stripped_content.split('\n')
    
    # Generate XML docs and collect insertions
    insertions = []  # (line_index, xml_line)
    
    for i, line in enumerate(code_lines):
        stripped = line.strip()
        if not stripped:
            continue
        
        indent = get_indent(line)
        
        # Type declarations
        type_m = is_type_declaration(stripped)
        if type_m:
            xml = generate_xml_for_type(stripped, indent)
            if xml:
                insertions.append((i, xml))
            continue
        
        # Constructor declarations (before method, since constructors look like methods)
        ctor_m = is_constructor_declaration(stripped)
        if ctor_m[0]:
            xml = generate_xml_for_constructor(stripped, indent)
            if xml:
                insertions.append((i, xml))
            continue
        
        # Method declarations
        method_m = is_method_declaration(stripped)
        if method_m[0]:
            xml = generate_xml_for_method(stripped, indent)
            if xml:
                insertions.append((i, xml))
            continue
        
        # Property declarations
        if is_property_declaration(stripped):
            xml = generate_xml_for_property(stripped, indent)
            if xml:
                insertions.append((i, xml))
            continue
        
        # Field declarations
        if is_field_declaration(stripped):
            xml = generate_xml_for_field(stripped, indent)
            if xml:
                insertions.append((i, xml))
            continue
        
        # Event declarations
        if is_event_declaration(stripped):
            xml = generate_xml_for_event(stripped, indent)
            if xml:
                insertions.append((i, xml))
            continue
    
    # Apply insertions in reverse order
    if insertions:
        for idx, xml_line in reversed(insertions):
            code_lines.insert(idx, xml_line)
    
    new_content = '\n'.join(header_lines + code_lines)
    was_modified = (new_content != content)
    
    return new_content, was_modified

# ─── Main loop ────────────────────────────────────────────────────────────────
def main():
    file_list_path = Path("/tmp/cs_files.txt")
    if not file_list_path.exists():
        print("ERROR: /tmp/cs_files.txt not found", file=sys.stderr)
        sys.exit(1)
    
    with open(file_list_path, 'r') as f:
        files = [line.strip() for line in f if line.strip()]
    
    cache = load_cache()
    processed_count = 0
    batch_count = 0
    total = len(files)
    
    for filepath in files:
        # Skip if already processed
        if cache.get(filepath, {}).get('status') == 'documented':
            continue
        
        new_content, was_modified = process_file(filepath)
        
        if new_content is None:
            cache[filepath] = {'status': 'error', 'timestamp': datetime.now(timezone.utc).isoformat()}
            save_cache(cache)
            print(f"{filepath} - error")
            continue
        
        if was_modified:
            try:
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(new_content)
            except (IOError, OSError) as e:
                print(f"WRITE ERROR: {filepath} - {e}", file=sys.stderr)
        
        cache[filepath] = {'status': 'documented', 'timestamp': datetime.now(timezone.utc).isoformat()}
        processed_count += 1
        batch_count += 1
        
        # Throttled build check every 1000
        if batch_count >= 1000:
            print(f"\n[BUILD CHECK] Processed {processed_count}/{total} files", file=sys.stderr)
            batch_count = 0
        
        # Save cache after each file
        save_cache(cache)
        
        print(f"{filepath} - documented")

if __name__ == '__main__':
    main()
