//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alis.Core.Graphic.Properties.osx.x64 {
    using System;
    
    
    /// <summary>
    /// The native graphic osx class
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NativeGraphicOsxX64 {
        
        /// <summary>
        /// The resource man
        /// </summary>
        private static System.Resources.ResourceManager resourceMan;
        
        /// <summary>
        /// The resource culture
        /// </summary>
        private static System.Globalization.CultureInfo resourceCulture;
        
        /// <summary>
        /// Initializes a new instance of the <see cref="NativeGraphicOsxX64"/> class
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NativeGraphicOsxX64() {
        }
        
        /// <summary>
        /// Gets the value of the resource manager
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Alis.Core.Graphic.Properties.osx.x64.NativeGraphicOsxX64", typeof(NativeGraphicOsxX64).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        /// Gets or sets the value of the culture
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Gets the value of the osx x64 cimgui
        /// </summary>
        internal static byte[] osx_x64_cimgui {
            get {
                object obj = ResourceManager.GetObject("osx_x64_cimgui", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx x64 sdl2
        /// </summary>
        internal static byte[] osx_x64_sdl2 {
            get {
                object obj = ResourceManager.GetObject("osx_x64_sdl2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx x64 sdl2 image
        /// </summary>
        internal static byte[] osx_x64_sdl2_image {
            get {
                object obj = ResourceManager.GetObject("osx_x64_sdl2_image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx x64 sdl2 ttf
        /// </summary>
        internal static byte[] osx_x64_sdl2_ttf {
            get {
                object obj = ResourceManager.GetObject("osx_x64_sdl2_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx x64 sdl2 mixer
        /// </summary>
        internal static byte[] osx_x64_sdl2_mixer {
            get {
                object obj = ResourceManager.GetObject("osx_x64_sdl2_mixer", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
