//----------------------------------------------------------------------------------------------------
// <author>Pablo Perdomo Falcón </author>
// <copyright file="Main.cs" company="Pabllopf">GNU General Public License v3.0</copyright>
//----------------------------------------------------------------------------------------------------
namespace Example_Core
{
    using System.Numerics;
    using Alis.Core;
    using Alis.Core.SFML;

    /// <summary>Example of videogame.</summary>
    public class Program
    {
        /// <summary>Defines the entry point of the application.</summary>
        /// <param name="args">The arguments.</param>
        public static void Main(string[] args)
        {
            //VideoGame.TestSFML();

            VideoGame.Builder()
                .Config(Config.Builder()
                    .Name("Ping Pong")
                    .Author("Pablo Perdomo Falcón")
                    .Debug(true)
                    .Time(Time.Builder()
                        .LimitFrameRate(false)
                        .TimeStep(0.01f)
                        .FrameRate(120)
                        .LimitFrameRate(true)
                    .Build())
                    .Window(WindowManager.Builder()
                            .Resolution(1920, 1080)
                            .WindowState(WindowState.Normal)
                            .Build())
                    .Build())

                 .SceneManager(SceneManager.Builder()
                    .Scene(Scene.Builder()
                        .Name("Menu")
                        .GameObject(GameObject.Builder()
                            .Name("controller")
                            .Transform(new Transform(new Vector3(-444), new Vector3(0f), new Vector3(110, 110, 0f)))
                            .Component(new Select())
                            .Component(new Sprite("background.png", -1))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("soundtrackController")
                            .Component(new AudioSource("menu.wav", true, 80.0f, true))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("startButton")
                            .Transform(new Transform(new Vector3(760.0f, 300.0f, 0), new Vector3(0.0f), new Vector3(7.0f)))
                            .Component(new Sprite("start_button.png"))

                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("exitButton")
                            .Transform(new Transform(new Vector3(760.0f, 500.0f, 0), new Vector3(0.0f), new Vector3(7.0f)))
                            .Component(new Sprite("exit_button.png"))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("1Button")
                            .Transform(new Transform(new Vector3(750.0f, 400.0f, 0), new Vector3(0.0f), new Vector3(3.5f)))
                            .Component(new Sprite("1.png"))
                            .Component(new Animator(0, new System.Collections.Generic.List<Animation>
                            {
                                new Animation("default", 0, 0.2f, "1.png", "11.png")
                            }))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("2Button")
                            .Transform(new Transform(new Vector3(750.0f, 600.0f, 0), new Vector3(0.0f), new Vector3(3.5f)))
                            .Component(new Sprite("2.png"))
                            .Component(new Animator(0, new System.Collections.Generic.List<Animation>
                            {
                                new Animation("default", 0, 0.2f, "2.png", "22.png")
                            }))
                            .Build())
                        .Build())
                    .Scene(Scene.Builder()
                        .Name("Game")
                        .GameObject(GameObject.Builder()
                            .Name("soundtrackController")
                            .Component(new AudioSource("ping.wav", true, 80.0f, true))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("topWall")
                            .Transform(new Transform(new Vector3(0, -40, 0), new Vector3(0), new Vector3(1)))
                            .Component(new Collision(new Vector2(1930, 40), false))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("bottomWall")
                            .Transform(new Transform(new Vector3(0, 1080, 0), new Vector3(0), new Vector3(1)))
                            .Component(new Collision(new Vector2(1930, 40), false))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("racket1Goal")
                            .Transform(new Transform(new Vector3(-40, 0, 0), new Vector3(0), new Vector3(1)))
                            .Component(new Collision(new Vector2(40, 1080), false))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("racket2Goal")
                            .Transform(new Transform(new Vector3(1920, 0, 0), new Vector3(0), new Vector3(1)))
                            .Component(new Collision(new Vector2(40, 1080), false))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("racket1")
                            .Transform(new Transform(new Vector3(51, 487, 0), new Vector3(0, 90, 0), new Vector3(1)))
                            .Component(new PointController())
                            .Component(new Move(Keyboard.W, Keyboard.S))
                            .Component(new Sprite("Button13.png"))
                            .Component(new Collision(new Vector2(105, 21), false))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("racket2")
                            .Transform(new Transform(new Vector3(1890, 487, 0), new Vector3(0, 90, 0), new Vector3(1)))
                            .Component(new PointController())
                            .Component(new Move(Keyboard.Up, Keyboard.Down))
                            .Component(new Sprite("Button14.png"))
                            .Component(new Collision(new Vector2(105, 21), false))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("ball")
                            .Transform(new Transform(new Vector3(956, 526, 0), new Vector3(0), new Vector3(1)))
                            .Component(new Sprite("background.png"))
                            .Component(new Collision(new Vector2(28, 28), false))
                            .Component(new BallController())
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("racket1point1")
                            .Transform(new Transform(new Vector3(50, 50, 0), new Vector3(0), new Vector3(1)))
                            .Component(new Sprite("heart_1.png"))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("racket1point2")
                            .Transform(new Transform(new Vector3(59, 50, 0), new Vector3(0), new Vector3(1)))
                            .Component(new Sprite("heart_1.png"))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("racket1point3")
                            .Transform(new Transform(new Vector3(68, 50, 0), new Vector3(0), new Vector3(1)))
                            .Component(new Sprite("heart_1.png"))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("racket2point1")
                            .Transform(new Transform(new Vector3(1852, 50, 0), new Vector3(0), new Vector3(1)))
                            .Component(new Sprite("heart_1.png"))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("racket2point2")
                            .Transform(new Transform(new Vector3(1843, 50, 0), new Vector3(0), new Vector3(1)))
                            .Component(new Sprite("heart_1.png"))
                            .Build())
                        .GameObject(GameObject.Builder()
                            .Name("racket2point3")
                            .Transform(new Transform(new Vector3(1834, 50, 0), new Vector3(0), new Vector3(1)))
                            .Component(new Sprite("heart_1.png"))
                            .Build())
                        .Build())
                  .Build())
            .Run();
        }
    }
}