//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alis.Core.Audio.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NativeAudioOsxARM64 {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NativeAudioOsxARM64() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Alis.Core.Audio.Properties.NativeAudioOsxARM64", typeof(NativeAudioOsxARM64).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] osx_arm64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_arm64_sdl2_mixer {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_sdl2_mixer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_x64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("osx_x64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osx_x64_sdl2_mixer {
            get {
                object obj = ResourceManager.GetObject("osx_x64_sdl2_mixer", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
