//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alis.Core.Audio.Properties.osx.arm64 {
    /// <summary>
    /// The native audio osx arm 64 sdl class
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NativeAudioOsxARM64SDL {
        
        /// <summary>
        /// The resource man
        /// </summary>
        private static System.Resources.ResourceManager resourceMan;
        
        /// <summary>
        /// The resource culture
        /// </summary>
        private static System.Globalization.CultureInfo resourceCulture;
        
        /// <summary>
        /// Initializes a new instance of the <see cref="NativeAudioOsxARM64SDL"/> class
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NativeAudioOsxARM64SDL() {
        }
        
        /// <summary>
        /// Gets the value of the resource manager
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Alis.Core.Audio.Properties.NativeAudioOsxARM64SDL", typeof(NativeAudioOsxARM64SDL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        /// Gets or sets the value of the culture
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Gets the value of the osx arm64 csfml audio
        /// </summary>
        internal static byte[] osx_arm64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx arm64 sdl2 mixer
        /// </summary>
        internal static byte[] osx_arm64_sdl2_mixer {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_sdl2_mixer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx x64 csfml audio
        /// </summary>
        internal static byte[] osx_x64_csfml_audio {
            get {
                object obj = ResourceManager.GetObject("osx_x64_csfml_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx x64 sdl2 mixer
        /// </summary>
        internal static byte[] osx_x64_sdl2_mixer {
            get {
                object obj = ResourceManager.GetObject("osx_x64_sdl2_mixer", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
