### YamlMime:ApiPage
title: Enum BodySettings
body:
- api1: Enum BodySettings
  id: Alis_Core_Physic_Dynamics_BodySettings
  src: https://github.com/pabllopf/Alis/blob/master/4_Operation/Physic/src/Dynamics/BodySettings.cs#L37
  metadata:
    uid: Alis.Core.Physic.Dynamics.BodySettings
    commentId: T:Alis.Core.Physic.Dynamics.BodySettings
- facts:
  - name: Namespace
    value:
      text: Alis.Core.Physic.Dynamics
      url: Alis.Core.Physic.Dynamics.html
  - name: Assembly
    value: Alis.dll
- markdown: The body flags enum
- code: >-
    [Flags]

    public enum BodySettings : byte
- h2: Fields
- parameters:
  - name: None
    default: "0"
    description: >+
      The unknown body flags

  - name: IslandFlag
    default: "1"
    description: >+
      The island flag body flags

  - name: AwakeFlag
    default: "2"
    description: >+
      The awake flag body flags

  - name: AutoSleepFlag
    default: "4"
    description: >+
      The auto sleep flag body flags

  - name: BulletFlag
    default: "8"
    description: >+
      The bullet flag body flags

  - name: FixedRotationFlag
    default: "16"
    description: >+
      The fixed rotation flag body flags

  - name: Enabled
    default: "32"
    description: >+
      The enabled body flags

  - name: IgnoreCcd
    default: "64"
    description: >+
      The ignore ccd body flags

languageId: csharp
metadata:
  description: The body flags enum
