### YamlMime:ApiPage
title: Class ConsoleLogConfig
body:
- api1: Class ConsoleLogConfig
  id: Alis_Core_Aspect_Logging_ConsoleLogConfig
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Logging/src/ConsoleLogConfig.cs#L37
  metadata:
    uid: Alis.Core.Aspect.Logging.ConsoleLogConfig
    commentId: T:Alis.Core.Aspect.Logging.ConsoleLogConfig
- facts:
  - name: Namespace
    value:
      text: Alis.Core.Aspect.Logging
      url: Alis.Core.Aspect.Logging.html
  - name: Assembly
    value: Alis.dll
- markdown: The console log config class
- code: public static class ConsoleLogConfig
- h4: Inheritance
- inheritance:
  - text: object
    url: https://learn.microsoft.com/dotnet/api/system.object
  - text: ConsoleLogConfig
    url: Alis.Core.Aspect.Logging.ConsoleLogConfig.html
- h4: Inherited Members
- list:
  - text: object.Equals(object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - text: object.Equals(object?, object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - text: object.GetHashCode()
    url: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - text: object.GetType()
    url: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - text: object.MemberwiseClone()
    url: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - text: object.ReferenceEquals(object?, object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - text: object.ToString()
    url: https://learn.microsoft.com/dotnet/api/system.object.tostring
- h2: Fields
- api3: ErrorMessageColor
  id: Alis_Core_Aspect_Logging_ConsoleLogConfig_ErrorMessageColor
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Logging/src/ConsoleLogConfig.cs#L62
  metadata:
    uid: Alis.Core.Aspect.Logging.ConsoleLogConfig.ErrorMessageColor
    commentId: F:Alis.Core.Aspect.Logging.ConsoleLogConfig.ErrorMessageColor
- markdown: Error text color
- code: private const ConsoleColor ErrorMessageColor = Red
- h4: Field Value
- parameters:
  - type:
    - text: ConsoleColor
      url: https://learn.microsoft.com/dotnet/api/system.consolecolor
- api3: EventMessageColor
  id: Alis_Core_Aspect_Logging_ConsoleLogConfig_EventMessageColor
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Logging/src/ConsoleLogConfig.cs#L72
  metadata:
    uid: Alis.Core.Aspect.Logging.ConsoleLogConfig.EventMessageColor
    commentId: F:Alis.Core.Aspect.Logging.ConsoleLogConfig.EventMessageColor
- markdown: Event text color
- code: private const ConsoleColor EventMessageColor = DarkMagenta
- h4: Field Value
- parameters:
  - type:
    - text: ConsoleColor
      url: https://learn.microsoft.com/dotnet/api/system.consolecolor
- api3: ExceptionMessageColor
  id: Alis_Core_Aspect_Logging_ConsoleLogConfig_ExceptionMessageColor
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Logging/src/ConsoleLogConfig.cs#L67
  metadata:
    uid: Alis.Core.Aspect.Logging.ConsoleLogConfig.ExceptionMessageColor
    commentId: F:Alis.Core.Aspect.Logging.ConsoleLogConfig.ExceptionMessageColor
- markdown: Exception text color
- code: private const ConsoleColor ExceptionMessageColor = DarkRed
- h4: Field Value
- parameters:
  - type:
    - text: ConsoleColor
      url: https://learn.microsoft.com/dotnet/api/system.consolecolor
- api3: InfoMessageColor
  id: Alis_Core_Aspect_Logging_ConsoleLogConfig_InfoMessageColor
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Logging/src/ConsoleLogConfig.cs#L42
  metadata:
    uid: Alis.Core.Aspect.Logging.ConsoleLogConfig.InfoMessageColor
    commentId: F:Alis.Core.Aspect.Logging.ConsoleLogConfig.InfoMessageColor
- markdown: Info text color
- code: private const ConsoleColor InfoMessageColor = DarkGreen
- h4: Field Value
- parameters:
  - type:
    - text: ConsoleColor
      url: https://learn.microsoft.com/dotnet/api/system.consolecolor
- api3: LogMessageColor
  id: Alis_Core_Aspect_Logging_ConsoleLogConfig_LogMessageColor
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Logging/src/ConsoleLogConfig.cs#L47
  metadata:
    uid: Alis.Core.Aspect.Logging.ConsoleLogConfig.LogMessageColor
    commentId: F:Alis.Core.Aspect.Logging.ConsoleLogConfig.LogMessageColor
- markdown: Log text color
- code: private const ConsoleColor LogMessageColor = White
- h4: Field Value
- parameters:
  - type:
    - text: ConsoleColor
      url: https://learn.microsoft.com/dotnet/api/system.consolecolor
- api3: TraceMessageColor
  id: Alis_Core_Aspect_Logging_ConsoleLogConfig_TraceMessageColor
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Logging/src/ConsoleLogConfig.cs#L52
  metadata:
    uid: Alis.Core.Aspect.Logging.ConsoleLogConfig.TraceMessageColor
    commentId: F:Alis.Core.Aspect.Logging.ConsoleLogConfig.TraceMessageColor
- markdown: Trace text color
- code: private const ConsoleColor TraceMessageColor = White
- h4: Field Value
- parameters:
  - type:
    - text: ConsoleColor
      url: https://learn.microsoft.com/dotnet/api/system.consolecolor
- api3: WarningMessageColor
  id: Alis_Core_Aspect_Logging_ConsoleLogConfig_WarningMessageColor
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Logging/src/ConsoleLogConfig.cs#L57
  metadata:
    uid: Alis.Core.Aspect.Logging.ConsoleLogConfig.WarningMessageColor
    commentId: F:Alis.Core.Aspect.Logging.ConsoleLogConfig.WarningMessageColor
- markdown: Warning text color
- code: private const ConsoleColor WarningMessageColor = DarkYellow
- h4: Field Value
- parameters:
  - type:
    - text: ConsoleColor
      url: https://learn.microsoft.com/dotnet/api/system.consolecolor
- h2: Methods
- api3: GetColorMessageByType(MessageType)
  id: Alis_Core_Aspect_Logging_ConsoleLogConfig_GetColorMessageByType_Alis_Core_Aspect_Logging_MessageType_
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Logging/src/ConsoleLogConfig.cs#L80
  metadata:
    uid: Alis.Core.Aspect.Logging.ConsoleLogConfig.GetColorMessageByType(Alis.Core.Aspect.Logging.MessageType)
    commentId: M:Alis.Core.Aspect.Logging.ConsoleLogConfig.GetColorMessageByType(Alis.Core.Aspect.Logging.MessageType)
- markdown: Gets the color message by type using the specified message type
- code: public static ConsoleColor GetColorMessageByType(MessageType messageType)
- h4: Parameters
- parameters:
  - name: messageType
    type:
    - text: MessageType
      url: Alis.Core.Aspect.Logging.MessageType.html
    description: The message type
- h4: Returns
- parameters:
  - type:
    - text: ConsoleColor
      url: https://learn.microsoft.com/dotnet/api/system.consolecolor
    description: The console color
- h4: Exceptions
- parameters:
  - type:
    - text: ArgumentOutOfRangeException
      url: https://learn.microsoft.com/dotnet/api/system.argumentoutofrangeexception
    description: "null"
languageId: csharp
metadata:
  description: The console log config class
