### YamlMime:ApiPage
title: Class TimeConfiguration
body:
- api1: Class TimeConfiguration
  id: Alis_Core_Aspect_Time_TimeConfiguration
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Time/src/TimeConfiguration.cs#L35
  metadata:
    uid: Alis.Core.Aspect.Time.TimeConfiguration
    commentId: T:Alis.Core.Aspect.Time.TimeConfiguration
- facts:
  - name: Namespace
    value:
      text: Alis.Core.Aspect.Time
      url: Alis.Core.Aspect.Time.html
  - name: Assembly
    value: Alis.dll
- markdown: The time class
- code: public class TimeConfiguration
- h4: Inheritance
- inheritance:
  - text: object
    url: https://learn.microsoft.com/dotnet/api/system.object
  - text: TimeConfiguration
    url: Alis.Core.Aspect.Time.TimeConfiguration.html
- h4: Inherited Members
- list:
  - text: object.Equals(object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - text: object.Equals(object?, object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - text: object.GetHashCode()
    url: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - text: object.GetType()
    url: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - text: object.MemberwiseClone()
    url: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - text: object.ReferenceEquals(object?, object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - text: object.ToString()
    url: https://learn.microsoft.com/dotnet/api/system.object.tostring
- h2: Constructors
- api3: TimeConfiguration(float, float, float)
  id: Alis_Core_Aspect_Time_TimeConfiguration__ctor_System_Single_System_Single_System_Single_
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Time/src/TimeConfiguration.cs#L43
  metadata:
    uid: Alis.Core.Aspect.Time.TimeConfiguration.#ctor(System.Single,System.Single,System.Single)
    commentId: M:Alis.Core.Aspect.Time.TimeConfiguration.#ctor(System.Single,System.Single,System.Single)
- markdown: Initializes a new instance of the <xref href="Alis.Core.Aspect.Time.TimeConfiguration" data-throw-if-not-resolved="false"></xref> class
- code: public TimeConfiguration(float fixedTimeStep = 0.016, float maximumAllowedTimeStep = 0.1, float timeScale = 1)
- h4: Parameters
- parameters:
  - name: fixedTimeStep
    type:
    - text: float
      url: https://learn.microsoft.com/dotnet/api/system.single
    description: The fixed time step
    optional: true
  - name: maximumAllowedTimeStep
    type:
    - text: float
      url: https://learn.microsoft.com/dotnet/api/system.single
    description: The maximum allowed time step
    optional: true
  - name: timeScale
    type:
    - text: float
      url: https://learn.microsoft.com/dotnet/api/system.single
    description: The time scale
    optional: true
- h2: Properties
- api3: FixedTimeStep
  id: Alis_Core_Aspect_Time_TimeConfiguration_FixedTimeStep
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Time/src/TimeConfiguration.cs#L53
  metadata:
    uid: Alis.Core.Aspect.Time.TimeConfiguration.FixedTimeStep
    commentId: P:Alis.Core.Aspect.Time.TimeConfiguration.FixedTimeStep
- markdown: A framerate-independent interval that dictates when physics calculations and FixedUpdate() events are performed.
- code: public float FixedTimeStep { get; set; }
- h4: Property Value
- parameters:
  - type:
    - text: float
      url: https://learn.microsoft.com/dotnet/api/system.single
- api3: LogOutput
  id: Alis_Core_Aspect_Time_TimeConfiguration_LogOutput
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Time/src/TimeConfiguration.cs#L71
  metadata:
    uid: Alis.Core.Aspect.Time.TimeConfiguration.LogOutput
    commentId: P:Alis.Core.Aspect.Time.TimeConfiguration.LogOutput
- markdown: Gets or sets the value of the log output
- code: public bool LogOutput { get; set; }
- h4: Property Value
- parameters:
  - type:
    - text: bool
      url: https://learn.microsoft.com/dotnet/api/system.boolean
- api3: MaximumAllowedTimeStep
  id: Alis_Core_Aspect_Time_TimeConfiguration_MaximumAllowedTimeStep
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Time/src/TimeConfiguration.cs#L59
  metadata:
    uid: Alis.Core.Aspect.Time.TimeConfiguration.MaximumAllowedTimeStep
    commentId: P:Alis.Core.Aspect.Time.TimeConfiguration.MaximumAllowedTimeStep
- markdown: >-
    A framerate-independent interval that caps the worst case scenario when frame-rate is low.

    Physics calculations and FixedUpdate() events will not be performed for longer time than specified.
- code: public float MaximumAllowedTimeStep { get; set; }
- h4: Property Value
- parameters:
  - type:
    - text: float
      url: https://learn.microsoft.com/dotnet/api/system.single
- api3: TimeScale
  id: Alis_Core_Aspect_Time_TimeConfiguration_TimeScale
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Time/src/TimeConfiguration.cs#L66
  metadata:
    uid: Alis.Core.Aspect.Time.TimeConfiguration.TimeScale
    commentId: P:Alis.Core.Aspect.Time.TimeConfiguration.TimeScale
- markdown: >-
    The speed at which time progresses.

    Change this value to simulate bullet-time effects.

    A value of 1 means real-time. A value of .5 means half speed; a value of 2 is double speed.
- code: public float TimeScale { get; set; }
- h4: Property Value
- parameters:
  - type:
    - text: float
      url: https://learn.microsoft.com/dotnet/api/system.single
languageId: csharp
metadata:
  description: The time class
