### YamlMime:ApiPage
title: Interface ISettings<TBuilder, TArgument>
body:
- api1: Interface ISettings<TBuilder, TArgument>
  id: Alis_Core_Aspect_Fluent_Words_ISettings_2
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Fluent/src/Words/ISettings.cs#L35
  metadata:
    uid: Alis.Core.Aspect.Fluent.Words.ISettings`2
    commentId: T:Alis.Core.Aspect.Fluent.Words.ISettings`2
- facts:
  - name: Namespace
    value:
      text: Alis.Core.Aspect.Fluent.Words
      url: Alis.Core.Aspect.Fluent.Words.html
  - name: Assembly
    value: Alis.dll
- markdown: The settings interface
- code: public interface ISettings<out TBuilder, in TArgument>
- h4: Type Parameters
- parameters:
  - name: TBuilder
  - name: TArgument
- h2: Methods
- api3: Settings(TArgument)
  id: Alis_Core_Aspect_Fluent_Words_ISettings_2_Settings__1_
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Fluent/src/Words/ISettings.cs#L42
  metadata:
    uid: Alis.Core.Aspect.Fluent.Words.ISettings`2.Settings(`1)
    commentId: M:Alis.Core.Aspect.Fluent.Words.ISettings`2.Settings(`1)
- markdown: Settingses the value
- code: TBuilder Settings(TArgument value)
- h4: Parameters
- parameters:
  - name: value
    type:
    - TArgument
    description: The value
- h4: Returns
- parameters:
  - type:
    - TBuilder
    description: The builder
languageId: csharp
metadata:
  description: The settings interface
