### YamlMime:ApiPage
title: Namespace Alis.Core.Aspect.Security
body:
- api1: Namespace Alis.Core.Aspect.Security
  id: Alis_Core_Aspect_Security
  metadata:
    uid: Alis.Core.Aspect.Security
    commentId: N:Alis.Core.Aspect.Security
- h3: Classes
- parameters:
  - type:
      text: SecureByte
      url: Alis.Core.Aspect.Security.SecureByte.html
    description: The secure byte class
  - type:
      text: SecureChar
      url: Alis.Core.Aspect.Security.SecureChar.html
    description: The secure char class
  - type:
      text: SecureDecimal
      url: Alis.Core.Aspect.Security.SecureDecimal.html
    description: The secure decimal class
  - type:
      text: SecureDouble
      url: Alis.Core.Aspect.Security.SecureDouble.html
    description: The secure double class
  - type:
      text: SecureFloat
      url: Alis.Core.Aspect.Security.SecureFloat.html
    description: The secure float class
  - type:
      text: SecureInt
      url: Alis.Core.Aspect.Security.SecureInt.html
    description: The secure int class
  - type:
      text: SecureLong
      url: Alis.Core.Aspect.Security.SecureLong.html
    description: The secure long class
  - type:
      text: SecureRandom
      url: Alis.Core.Aspect.Security.SecureRandom.html
    description: The secure random class
  - type:
      text: SecureString
      url: Alis.Core.Aspect.Security.SecureString.html
    description: The secure string class
languageId: csharp
