### YamlMime:ApiPage
title: Class SettingsBuilder
body:
- api1: Class SettingsBuilder
  id: Alis_Builder_Core_Ecs_System_Setting_SettingsBuilder
  src: https://github.com/pabllopf/Alis/blob/master/2_Application/Alis/src/Builder/Core/Ecs/System/Setting/SettingsBuilder.cs#L54
  metadata:
    uid: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder
    commentId: T:Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder
- facts:
  - name: Namespace
    value:
      text: Alis.Builder.Core.Ecs.System.Setting
      url: Alis.Builder.Core.Ecs.System.Setting.html
  - name: Assembly
    value: Alis.dll
- markdown: Setting builder
- code: 'public class SettingsBuilder : IBuild<Settings>, IAudio<SettingsBuilder, Func<AudioSettingBuilder, AudioSetting>>, IGeneral<SettingsBuilder, Func<GeneralSettingBuilder, GeneralSetting>>, IGraphic<SettingsBuilder, Func<GraphicSettingBuilder, GraphicSetting>>, IInput<SettingsBuilder, Func<InputSettingBuilder, InputSetting>>, INetwork<SettingsBuilder, Func<NetworkSettingBuilder, NetworkSetting>>, IPhysic<SettingsBuilder, Func<PhysicSettingBuilder, PhysicSetting>>, IScene<SettingsBuilder, Func<SceneSettingBuilder, SceneSetting>>'
- h4: Inheritance
- inheritance:
  - text: object
    url: https://learn.microsoft.com/dotnet/api/system.object
  - text: SettingsBuilder
    url: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.html
- h4: Implements
- list:
  - text: IBuild<Settings>
    url: Alis.Core.Aspect.Fluent.IBuild-1.html
  - text: IAudio<SettingsBuilder, Func<AudioSettingBuilder, AudioSetting>>
    url: Alis.Core.Aspect.Fluent.Words.IAudio-2.html
  - text: IGeneral<SettingsBuilder, Func<GeneralSettingBuilder, GeneralSetting>>
    url: Alis.Core.Aspect.Fluent.Words.IGeneral-2.html
  - text: IGraphic<SettingsBuilder, Func<GraphicSettingBuilder, GraphicSetting>>
    url: Alis.Core.Aspect.Fluent.Words.IGraphic-2.html
  - text: IInput<SettingsBuilder, Func<InputSettingBuilder, InputSetting>>
    url: Alis.Core.Aspect.Fluent.Words.IInput-2.html
  - text: INetwork<SettingsBuilder, Func<NetworkSettingBuilder, NetworkSetting>>
    url: Alis.Core.Aspect.Fluent.Words.INetwork-2.html
  - text: IPhysic<SettingsBuilder, Func<PhysicSettingBuilder, PhysicSetting>>
    url: Alis.Core.Aspect.Fluent.Words.IPhysic-2.html
  - text: IScene<SettingsBuilder, Func<SceneSettingBuilder, SceneSetting>>
    url: Alis.Core.Aspect.Fluent.Words.IScene-2.html
- h4: Inherited Members
- list:
  - text: object.Equals(object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - text: object.Equals(object?, object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - text: object.GetHashCode()
    url: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - text: object.GetType()
    url: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - text: object.MemberwiseClone()
    url: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - text: object.ReferenceEquals(object?, object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - text: object.ToString()
    url: https://learn.microsoft.com/dotnet/api/system.object.tostring
- h2: Fields
- api3: settingBase
  id: Alis_Builder_Core_Ecs_System_Setting_SettingsBuilder_settingBase
  src: https://github.com/pabllopf/Alis/blob/master/2_Application/Alis/src/Builder/Core/Ecs/System/Setting/SettingsBuilder.cs#L67
  metadata:
    uid: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.settingBase
    commentId: F:Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.settingBase
- markdown: The setting base
- code: private readonly Settings settingBase
- h4: Field Value
- parameters:
  - type:
    - text: Settings
      url: Alis.Core.Ecs.System.Setting.Settings.html
- h2: Methods
- api3: Audio(Func<AudioSettingBuilder, AudioSetting>)
  id: Alis_Builder_Core_Ecs_System_Setting_SettingsBuilder_Audio_System_Func_Alis_Builder_Core_Ecs_System_Setting_Audio_AudioSettingBuilder_Alis_Core_Ecs_System_Setting_Audio_AudioSetting__
  src: https://github.com/pabllopf/Alis/blob/master/2_Application/Alis/src/Builder/Core/Ecs/System/Setting/SettingsBuilder.cs#L74
  metadata:
    uid: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.Audio(System.Func{Alis.Builder.Core.Ecs.System.Setting.Audio.AudioSettingBuilder,Alis.Core.Ecs.System.Setting.Audio.AudioSetting})
    commentId: M:Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.Audio(System.Func{Alis.Builder.Core.Ecs.System.Setting.Audio.AudioSettingBuilder,Alis.Core.Ecs.System.Setting.Audio.AudioSetting})
- markdown: Audio the value
- code: public SettingsBuilder Audio(Func<AudioSettingBuilder, AudioSetting> value)
- h4: Parameters
- parameters:
  - name: value
    type:
    - text: Func
      url: https://learn.microsoft.com/dotnet/api/system.func-2
    - <
    - text: AudioSettingBuilder
      url: Alis.Builder.Core.Ecs.System.Setting.Audio.AudioSettingBuilder.html
    - ','
    - " "
    - text: AudioSetting
      url: Alis.Core.Ecs.System.Setting.Audio.AudioSetting.html
    - '>'
    description: The value
- h4: Returns
- parameters:
  - type:
    - text: SettingsBuilder
      url: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.html
    description: The settings builder
- api3: Build()
  id: Alis_Builder_Core_Ecs_System_Setting_SettingsBuilder_Build
  src: https://github.com/pabllopf/Alis/blob/master/2_Application/Alis/src/Builder/Core/Ecs/System/Setting/SettingsBuilder.cs#L84
  metadata:
    uid: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.Build
    commentId: M:Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.Build
- markdown: Build setting
- code: public Settings Build()
- h4: Returns
- parameters:
  - type:
    - text: Settings
      url: Alis.Core.Ecs.System.Setting.Settings.html
    description: ''
- api3: General(Func<GeneralSettingBuilder, GeneralSetting>)
  id: Alis_Builder_Core_Ecs_System_Setting_SettingsBuilder_General_System_Func_Alis_Builder_Core_Ecs_System_Setting_General_GeneralSettingBuilder_Alis_Core_Ecs_System_Setting_General_GeneralSetting__
  src: https://github.com/pabllopf/Alis/blob/master/2_Application/Alis/src/Builder/Core/Ecs/System/Setting/SettingsBuilder.cs#L91
  metadata:
    uid: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.General(System.Func{Alis.Builder.Core.Ecs.System.Setting.General.GeneralSettingBuilder,Alis.Core.Ecs.System.Setting.General.GeneralSetting})
    commentId: M:Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.General(System.Func{Alis.Builder.Core.Ecs.System.Setting.General.GeneralSettingBuilder,Alis.Core.Ecs.System.Setting.General.GeneralSetting})
- markdown: Generals the value
- code: public SettingsBuilder General(Func<GeneralSettingBuilder, GeneralSetting> value)
- h4: Parameters
- parameters:
  - name: value
    type:
    - text: Func
      url: https://learn.microsoft.com/dotnet/api/system.func-2
    - <
    - text: GeneralSettingBuilder
      url: Alis.Builder.Core.Ecs.System.Setting.General.GeneralSettingBuilder.html
    - ','
    - " "
    - text: GeneralSetting
      url: Alis.Core.Ecs.System.Setting.General.GeneralSetting.html
    - '>'
    description: The value
- h4: Returns
- parameters:
  - type:
    - text: SettingsBuilder
      url: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.html
    description: The settings builder
- api3: Graphic(Func<GraphicSettingBuilder, GraphicSetting>)
  id: Alis_Builder_Core_Ecs_System_Setting_SettingsBuilder_Graphic_System_Func_Alis_Builder_Core_Ecs_System_Setting_Graphic_GraphicSettingBuilder_Alis_Core_Ecs_System_Setting_Graphic_GraphicSetting__
  src: https://github.com/pabllopf/Alis/blob/master/2_Application/Alis/src/Builder/Core/Ecs/System/Setting/SettingsBuilder.cs#L102
  metadata:
    uid: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.Graphic(System.Func{Alis.Builder.Core.Ecs.System.Setting.Graphic.GraphicSettingBuilder,Alis.Core.Ecs.System.Setting.Graphic.GraphicSetting})
    commentId: M:Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.Graphic(System.Func{Alis.Builder.Core.Ecs.System.Setting.Graphic.GraphicSettingBuilder,Alis.Core.Ecs.System.Setting.Graphic.GraphicSetting})
- markdown: Graphics the value
- code: public SettingsBuilder Graphic(Func<GraphicSettingBuilder, GraphicSetting> value)
- h4: Parameters
- parameters:
  - name: value
    type:
    - text: Func
      url: https://learn.microsoft.com/dotnet/api/system.func-2
    - <
    - text: GraphicSettingBuilder
      url: Alis.Builder.Core.Ecs.System.Setting.Graphic.GraphicSettingBuilder.html
    - ','
    - " "
    - text: GraphicSetting
      url: Alis.Core.Ecs.System.Setting.Graphic.GraphicSetting.html
    - '>'
    description: The value
- h4: Returns
- parameters:
  - type:
    - text: SettingsBuilder
      url: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.html
    description: The settings builder
- api3: Input(Func<InputSettingBuilder, InputSetting>)
  id: Alis_Builder_Core_Ecs_System_Setting_SettingsBuilder_Input_System_Func_Alis_Builder_Core_Ecs_System_Setting_Input_InputSettingBuilder_Alis_Core_Ecs_System_Setting_Input_InputSetting__
  src: https://github.com/pabllopf/Alis/blob/master/2_Application/Alis/src/Builder/Core/Ecs/System/Setting/SettingsBuilder.cs#L114
  metadata:
    uid: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.Input(System.Func{Alis.Builder.Core.Ecs.System.Setting.Input.InputSettingBuilder,Alis.Core.Ecs.System.Setting.Input.InputSetting})
    commentId: M:Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.Input(System.Func{Alis.Builder.Core.Ecs.System.Setting.Input.InputSettingBuilder,Alis.Core.Ecs.System.Setting.Input.InputSetting})
- markdown: Inputs the value
- code: public SettingsBuilder Input(Func<InputSettingBuilder, InputSetting> value)
- h4: Parameters
- parameters:
  - name: value
    type:
    - text: Func
      url: https://learn.microsoft.com/dotnet/api/system.func-2
    - <
    - text: InputSettingBuilder
      url: Alis.Builder.Core.Ecs.System.Setting.Input.InputSettingBuilder.html
    - ','
    - " "
    - text: InputSetting
      url: Alis.Core.Ecs.System.Setting.Input.InputSetting.html
    - '>'
    description: The value
- h4: Returns
- parameters:
  - type:
    - text: SettingsBuilder
      url: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.html
    description: The settings builder
- api3: Network(Func<NetworkSettingBuilder, NetworkSetting>)
  id: Alis_Builder_Core_Ecs_System_Setting_SettingsBuilder_Network_System_Func_Alis_Builder_Core_Ecs_System_Setting_Network_NetworkSettingBuilder_Alis_Core_Ecs_System_Setting_Network_NetworkSetting__
  src: https://github.com/pabllopf/Alis/blob/master/2_Application/Alis/src/Builder/Core/Ecs/System/Setting/SettingsBuilder.cs#L125
  metadata:
    uid: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.Network(System.Func{Alis.Builder.Core.Ecs.System.Setting.Network.NetworkSettingBuilder,Alis.Core.Ecs.System.Setting.Network.NetworkSetting})
    commentId: M:Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.Network(System.Func{Alis.Builder.Core.Ecs.System.Setting.Network.NetworkSettingBuilder,Alis.Core.Ecs.System.Setting.Network.NetworkSetting})
- markdown: Networks the value
- code: public SettingsBuilder Network(Func<NetworkSettingBuilder, NetworkSetting> value)
- h4: Parameters
- parameters:
  - name: value
    type:
    - text: Func
      url: https://learn.microsoft.com/dotnet/api/system.func-2
    - <
    - text: NetworkSettingBuilder
      url: Alis.Builder.Core.Ecs.System.Setting.Network.NetworkSettingBuilder.html
    - ','
    - " "
    - text: NetworkSetting
      url: Alis.Core.Ecs.System.Setting.Network.NetworkSetting.html
    - '>'
    description: The value
- h4: Returns
- parameters:
  - type:
    - text: SettingsBuilder
      url: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.html
    description: The settings builder
- api3: Physic(Func<PhysicSettingBuilder, PhysicSetting>)
  id: Alis_Builder_Core_Ecs_System_Setting_SettingsBuilder_Physic_System_Func_Alis_Builder_Core_Ecs_System_Setting_Physic_PhysicSettingBuilder_Alis_Core_Ecs_System_Setting_Physic_PhysicSetting__
  src: https://github.com/pabllopf/Alis/blob/master/2_Application/Alis/src/Builder/Core/Ecs/System/Setting/SettingsBuilder.cs#L136
  metadata:
    uid: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.Physic(System.Func{Alis.Builder.Core.Ecs.System.Setting.Physic.PhysicSettingBuilder,Alis.Core.Ecs.System.Setting.Physic.PhysicSetting})
    commentId: M:Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.Physic(System.Func{Alis.Builder.Core.Ecs.System.Setting.Physic.PhysicSettingBuilder,Alis.Core.Ecs.System.Setting.Physic.PhysicSetting})
- markdown: Physics the value
- code: public SettingsBuilder Physic(Func<PhysicSettingBuilder, PhysicSetting> value)
- h4: Parameters
- parameters:
  - name: value
    type:
    - text: Func
      url: https://learn.microsoft.com/dotnet/api/system.func-2
    - <
    - text: PhysicSettingBuilder
      url: Alis.Builder.Core.Ecs.System.Setting.Physic.PhysicSettingBuilder.html
    - ','
    - " "
    - text: PhysicSetting
      url: Alis.Core.Ecs.System.Setting.Physic.PhysicSetting.html
    - '>'
    description: The value
- h4: Returns
- parameters:
  - type:
    - text: SettingsBuilder
      url: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.html
    description: The settings builder
- api3: Scene(Func<SceneSettingBuilder, SceneSetting>)
  id: Alis_Builder_Core_Ecs_System_Setting_SettingsBuilder_Scene_System_Func_Alis_Builder_Core_Ecs_System_Setting_Scene_SceneSettingBuilder_Alis_Core_Ecs_System_Setting_Scene_SceneSetting__
  src: https://github.com/pabllopf/Alis/blob/master/2_Application/Alis/src/Builder/Core/Ecs/System/Setting/SettingsBuilder.cs#L147
  metadata:
    uid: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.Scene(System.Func{Alis.Builder.Core.Ecs.System.Setting.Scene.SceneSettingBuilder,Alis.Core.Ecs.System.Setting.Scene.SceneSetting})
    commentId: M:Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.Scene(System.Func{Alis.Builder.Core.Ecs.System.Setting.Scene.SceneSettingBuilder,Alis.Core.Ecs.System.Setting.Scene.SceneSetting})
- markdown: Scenes the value
- code: public SettingsBuilder Scene(Func<SceneSettingBuilder, SceneSetting> value)
- h4: Parameters
- parameters:
  - name: value
    type:
    - text: Func
      url: https://learn.microsoft.com/dotnet/api/system.func-2
    - <
    - text: SceneSettingBuilder
      url: Alis.Builder.Core.Ecs.System.Setting.Scene.SceneSettingBuilder.html
    - ','
    - " "
    - text: SceneSetting
      url: Alis.Core.Ecs.System.Setting.Scene.SceneSetting.html
    - '>'
    description: The value
- h4: Returns
- parameters:
  - type:
    - text: SettingsBuilder
      url: Alis.Builder.Core.Ecs.System.Setting.SettingsBuilder.html
    description: The settings builder
languageId: csharp
metadata:
  description: Setting builder
