### YamlMime:ApiPage
title: Interface IConfiguration<TBuilder, TArgument>
body:
- api1: Interface IConfiguration<TBuilder, TArgument>
  id: Alis_Core_Aspect_Fluent_Words_IConfiguration_2
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Fluent/src/Words/IConfiguration.cs#L35
  metadata:
    uid: Alis.Core.Aspect.Fluent.Words.IConfiguration`2
    commentId: T:Alis.Core.Aspect.Fluent.Words.IConfiguration`2
- facts:
  - name: Namespace
    value:
      text: Alis.Core.Aspect.Fluent.Words
      url: Alis.Core.Aspect.Fluent.Words.html
  - name: Assembly
    value: Alis.dll
- markdown: The configuration interface
- code: public interface IConfiguration<out TBuilder, in TArgument>
- h4: Type Parameters
- parameters:
  - name: TBuilder
  - name: TArgument
- h2: Methods
- api3: Configuration(TArgument)
  id: Alis_Core_Aspect_Fluent_Words_IConfiguration_2_Configuration__1_
  src: https://github.com/pabllopf/Alis/blob/master/6_Ideation/Fluent/src/Words/IConfiguration.cs#L42
  metadata:
    uid: Alis.Core.Aspect.Fluent.Words.IConfiguration`2.Configuration(`1)
    commentId: M:Alis.Core.Aspect.Fluent.Words.IConfiguration`2.Configuration(`1)
- markdown: Configurations the value
- code: TBuilder Configuration(TArgument value)
- h4: Parameters
- parameters:
  - name: value
    type:
    - TArgument
    description: The value
- h4: Returns
- parameters:
  - type:
    - TBuilder
    description: The builder
languageId: csharp
metadata:
  description: The configuration interface
