//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alis.Core.Input.Properties {
    using System;
    
    
    /// <summary>
    /// The native input class
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NativeInput {
        
        /// <summary>
        /// The resource man
        /// </summary>
        private static System.Resources.ResourceManager resourceMan;
        
        /// <summary>
        /// The resource culture
        /// </summary>
        private static System.Globalization.CultureInfo resourceCulture;
        
        /// <summary>
        /// Initializes a new instance of the <see cref="NativeInput"/> class
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NativeInput() {
        }
        
        /// <summary>
        /// Gets the value of the resource manager
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Alis.Core.Input.Properties.NativeInput", typeof(NativeInput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        /// Gets or sets the value of the culture
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Gets the value of the linux arm64 sdl2
        /// </summary>
        internal static byte[] linux_arm64_SDL2 {
            get {
                object obj = ResourceManager.GetObject("linux_arm64_SDL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the linux x64 sdl2
        /// </summary>
        internal static byte[] linux_x64_SDL2 {
            get {
                object obj = ResourceManager.GetObject("linux_x64_SDL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the linux x86 sdl2
        /// </summary>
        internal static byte[] linux_x86_SDL2 {
            get {
                object obj = ResourceManager.GetObject("linux_x86_SDL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx arm64 sdl2
        /// </summary>
        internal static byte[] osx_arm64_SDL2 {
            get {
                object obj = ResourceManager.GetObject("osx_arm64_SDL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the osx x64 sdl2
        /// </summary>
        internal static byte[] osx_x64_SDL2 {
            get {
                object obj = ResourceManager.GetObject("osx_x64_SDL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the win arm64 sdl2
        /// </summary>
        internal static byte[] win_arm64_SDL2 {
            get {
                object obj = ResourceManager.GetObject("win_arm64_SDL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the win x64 sdl2
        /// </summary>
        internal static byte[] win_x64_SDL2 {
            get {
                object obj = ResourceManager.GetObject("win_x64_SDL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Gets the value of the win x86 sdl2
        /// </summary>
        internal static byte[] win_x86_SDL2 {
            get {
                object obj = ResourceManager.GetObject("win_x86_SDL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
