name: "[ALIS][SONARCLOUD]"

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
  
jobs:
  build-and-analyze:
    timeout-minutes: 35
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      discussions: write
      issues: write
      pages: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    if: contains(github.event.head_commit.message, 'fix:')
    runs-on: macos-15-intel

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.x.x'

      - name: SonarQube Scan
        run: |
          dotnet tool install --global coverlet.console --version 6.0.4
          dotnet tool install --global dotnet-sonarscanner --version 8.0.2
      
          dotnet sonarscanner begin \
            /k:"${{ secrets.SONAR_PROJECT_KEY }}" \
            /o:"${{ secrets.SONAR_ORGANIZATION }}" \
            /d:sonar.scanner.scanAll=false \
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.scanner.skipJreProvisioning=false \
            /d:sonar.language=cs \
            /d:sonar.dotnet.version=8.0 \
            /d:sonar.verbose=false \
            /d:sonar.exclusions="**/runtimes/**,**/obj/**,**/sample/**,**/test/**,**/docs/**,**/*.generated.cs,**/*.jpg,**/*.md,**/*.jpeg,**/*.png,**/*.gif,**/*.pdf,**/*.docx,**/*.xlsx,**/*.zip,**/*.ico" \
            /d:sonar.cs.opencover.reportsPaths="./.test/**/*.opencover.xml"

          dotnet build -c Debug --verbosity quiet -f net8.0 ./alis_design.slnx
          dotnet test --no-build -m:1 --verbosity quiet -f net8.0 -c Debug ./alis_design.slnx --collect "XPlat Code Coverage;Format=opencover" --results-directory ./.test --diag:logs/log.txt
      
          dotnet sonarscanner end \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          
      - name: Upload logs/log.txt
        uses: actions/upload-artifact@v7
        with:
          name: logs
          path: logs/log.txt
          
      - name: show logs/log.txt
        run: |
          cat logs/log.txt

