name: "[DEV][TEST]"

on:
  push:
    branches: [ master ]

jobs:
  macos_12_x64:
    if: "contains(github.event.head_commit.message, 'test:')"
    runs-on: macos-12
    env:
      GITHUB_ACTIONS_CACHE_DISABLED: true
    steps:
      - name: Check
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.0.103
            3.1.426
            5.0.408
            6.0.420
            7.0.408
            8.0.202

      - name: Dotnet test Debug
        run: dotnet test alis.sln -c Debug

      - uses: dorny/test-reporter@v1
        with:
          name: MacOs 12 x64 Test Report                  # Name of the check run which will be created
          path: '.test/**/**/*.trx'                     # Path to test results (inside artifact .zip)
          reporter: dotnet-trx              # Format of test results
  
  windows_2022_x64:
    if: "contains(github.event.head_commit.message, 'test:')"
    runs-on: windows-2022
    env:
      GITHUB_ACTIONS_CACHE_DISABLED: true
    steps:
      - name: Check
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: clean_bin_sln
        shell: cmd
        run: FOR /d /r . %%d IN (bin) DO @IF EXIST "%%d" rd /s /q "%%d"

      - name: clean_obj_sln
        shell: cmd
        run: FOR /d /r . %%d IN (obj) DO @IF EXIST "%%d" rd /s /q "%%d"

      - name: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.0.103
            3.1.426
            5.0.408
            6.0.420
            7.0.408
            8.0.202

      - name: Dotnet test Debug
        shell: cmd
        run: dotnet test alis.sln -c Debug

      - uses: dorny/test-reporter@v1
        with:
          name: Windows 2022 x64 Test Report                  # Name of the check run which will be created
          path: '.test/**/**/*.trx'                     # Path to test results (inside artifact .zip)
          reporter: dotnet-trx              # Format of test results
  
  ubuntu_22_04_x64:
    if: "contains(github.event.head_commit.message, 'test:')"
    runs-on: ubuntu-22.04
    env:
      GITHUB_ACTIONS_CACHE_DISABLED: true
    steps:
      - name: Check
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.0.103
            3.1.426
            5.0.408
            6.0.420
            7.0.408
            8.0.202

      - name: Dotnet test Debug
        run: dotnet test alis.sln -c Debug

      - uses: dorny/test-reporter@v1
        with:
          name: Ubuntu 22_04 x64 Test Report                 # Name of the check run which will be created
          path: '.test/**/**/*.trx'                     # Path to test results (inside artifact .zip)
          reporter: dotnet-trx              # Format of test results
