name: "[DEV][TEST]"

on:
  push:
    branches: [ master ]

jobs:
  macos_12_x64:
    if: "contains(github.event.head_commit.message, 'test:')"
    runs-on: macos-12
    env:
      GITHUB_ACTIONS_CACHE_DISABLED: true
    steps:
      - name: Check
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.0.103
            3.1.426
            5.0.408
            6.0.420
            7.0.408
            8.0.202

      - name: Install dependencies with Homebrew
        run: |
          brew install sdl2 sdl2_image sdl2_ttf ffmpeg
          brew link ffmpeg

      - name: Dotnet test Debug
        run: dotnet test alis.sln -c Debug --nologo -warnaserror 2>/dev/null

      - uses: dorny/test-reporter@v1
        with:
          name: MacOs 12 x64 Test Report
          path: '.test/**/**/*.trx'
          reporter: dotnet-trx
  
  windows_2022_x64:
    if: "contains(github.event.head_commit.message, 'test:')"
    runs-on: windows-2022
    env:
      GITHUB_ACTIONS_CACHE_DISABLED: true
    steps:
      - name: Check
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Download and Install SDL2
        run: |
          curl -LO https://www.libsdl.org/release/SDL2-devel-2.0.22-VC.zip
          curl -LO https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip
          curl -LO https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip
          Expand-Archive -Path SDL2-devel-2.0.22-VC.zip -DestinationPath $env:USERPROFILE\sdl2
          Expand-Archive -Path SDL2_image-devel-2.0.5-VC.zip -DestinationPath $env:USERPROFILE\sdl2
          Expand-Archive -Path SDL2_ttf-devel-2.0.15-VC.zip -DestinationPath $env:USERPROFILE\sdl2
          setx /M PATH "%PATH%;$env:USERPROFILE\sdl2\SDL2-2.0.22\lib\x64;$env:USERPROFILE\sdl2\SDL2_image-2.0.5\lib\x64;$env:USERPROFILE\sdl2\SDL2_ttf-2.0.15\lib\x64"
  
      - name: Install ffmpeg
        run: |
          choco install ffmpeg -y

      - name: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.0.103
            3.1.426
            5.0.408
            6.0.420
            7.0.408
            8.0.202

      - name: Dotnet test Debug
        shell: cmd
        run: dotnet test alis.sln -c Debug --nologo -warnaserror 2>nul

      - uses: dorny/test-reporter@v1
        with:
          name: Windows 2022 x64 Test Report
          path: '.test/**/**/*.trx'
          reporter: dotnet-trx
  
  ubuntu_22_04_x64:
    if: "contains(github.event.head_commit.message, 'test:')"
    runs-on: ubuntu-22.04
    env:
      GITHUB_ACTIONS_CACHE_DISABLED: true
    steps:
      - name: Check
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
  
      - name: Install SDL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-image-dev libsdl2-ttf-dev ffmpeg libsdl2-dev
  
      - name: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.0.103
            3.1.426
            5.0.408
            6.0.420
            7.0.408
            8.0.202
  
      - name: Dotnet test Debug
        run: dotnet test alis.sln -c Debug --nologo -warnaserror 2>/dev/null
  
      - uses: dorny/test-reporter@v1
        with:
          name: Ubuntu 22_04 x64 Test Report
          path: '.test/**/**/*.trx'
          reporter: dotnet-trx

