# Run test of the framework.
name: "[DEV][TEST][LINUX]"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  
jobs:
  CommentCode:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: develop

    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          2.1.x
          3.1.x
          5.0.x
          6.0.x

    - name: Install tool
      run: dotnet tool install --global dotnet-document --version 0.1.4-alpha

    - name: Comment code
      run: dotnet document apply ./alis.sln 
    
    - name: Commit the changes of document code
      run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git config core.autocrlf false
         git add .
         git commit -m "generated automatic comments on code by actions"
         git push

  Fast_Test:
    needs: CommentCode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln


  Linux_Latest:
    needs: Fast_Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln

  Linux_v22_04:
    needs: Fast_Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln

  Linux_v18_04:
    needs: Fast_Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln

  Macos_Latest:
    needs: Fast_Test
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln

  Macos_v12_0:
    needs: Fast_Test
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln

  Macos_v10_15:
    needs: Fast_Test
    runs-on: macos-10.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln

  Windows_Latest:
    needs: Fast_Test
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln
    
  Windows_v2019:
    needs: Fast_Test
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln
  
  Windows_v2016:
    needs: Fast_Test
    runs-on: windows-2016
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln