# Run test of the framework.
name: "[DEV][TEST][WINDOWS]"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  
jobs:
  Latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln
    
  v2019:
    name: windows-2019
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln
  
  v2016:
    name: windows-2016
    runs-on: windows-2016
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln
