name: "[DEV][TEST]"

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.git/**'
      - '.config/**'

jobs:
  macos_12_x64:
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master
          
      - name: Setup dotnet
        uses: actions/checkout@v4
        with:
          dotnet-version: |
            3.0.103
            3.1.426
            5.0.408
            6.0.420
            7.0.408
            8.0.202
            
      - name: Dotnet test Debug
        run: dotnet test alis.sln -c Debug
  
  windows_2022_x64:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup dotnet
        uses: actions/checkout@v4
        with:
          dotnet-version: |
            3.0.x
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x

      - name: Dotnet test Debug
        run: dotnet test alis.sln -c Debug
  
  ubuntu_22_04_x64:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup dotnet
        uses: actions/checkout@v4
        with:
          dotnet-version: |
            3.0.x
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x

      - name: Dotnet test Debug
        run: dotnet test alis.sln -c Debug
