name: "[PRO][PUBLISH][NUGET]"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Nugets:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          2.1.x
          3.1.x
          5.0.x
          6.0.x
    
    - name: "alis.aspect.time.csproj"
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH:  ./6_ideation/time/alis.aspect.time.csproj
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
        NUGET_KEY: ${{secrets.NUGET}}
        NUGET_SOURCE: https://api.nuget.org
        TAG_COMMIT: true
        TAG_FORMAT: v*