name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 ** *'

jobs:
  Generating_Documentation:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Cache_doc
      id: cache-doc
      uses: actions/cache@v2
      with:
        path: temp-doc
        key: ${{ runner.os }}-doc
      
    - name: Change Directory 
      run: cd scripts
      
    - name: Show Directory 
      run: dir
      
    - name: Build Doc
      run: .\\scripts\\Document_Web.bat
    
    - name: Update web
      run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git config core.autocrlf false
         git add .
         git commit -m "generated automatic documentation by actions"
         git push
        
