# Run test of the framework.
name: "[PRO][TEST][LINUX]"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
 
jobs:
  Latest:
    name: "ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln

  v22_04:
    name: "ubuntu-22.04"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln

  v18_04:
    name: "ubuntu-18.04"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Dotnet test
        run: dotnet test alis.sln

  