name: "[PRO][BENCHMARK]"

on:
  push:
    branches: [ master ]

jobs:
  
  Create_Packages:
    if: "contains(github.event.head_commit.message, 'benchmark:')"
    runs-on: macos-13
    steps:
      - name: Check
        uses: actions/checkout@v4
        with:
          ref: master
          fetch: 0

      - name: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.0.103
            3.1.426
            5.0.408
            6.0.420
            7.0.408
            8.0.202
            9.x.x

      - name: Install dependencies with Homebrew
        run: |
          brew install sdl2 sdl2_image sdl2_ttf ffmpeg 
      
      - name: Run Benchmarks
        run: |
          DATE=$(date +%Y-%m-%d)
          mkdir -p ./docs/benchmarks/$DATE
          dotnet run -c Release --project 2_Application/Alis/benchmark/Alis.Benchmark.csproj -- --exporters markdown > ./docs/benchmarks/$DATE/results.md
    
      - name: git config --global user.name github-actions
        run: git config --global user.name "${{ secrets.USER_NAME }}"

      - name: git config --global user.email github-actions@github.com
        run: git config --global user.email "${{ secrets.USER_EMAIL }}"

      - name: git config user.name
        run: git config user.name

      - name: git config user.email
        run: git config user.email

      - name: Find common ancestor
        run: git merge-base --fork-point origin/master

      - name: Import bot's GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: git fetch
        run: git fetch

      - name: git checkout master
        run: git checkout master

      - name: git pull
        run: git pull

      - name: git add .
        run: git add .

      - name: git commit -S -m "Create the packages of version '$VERSIONFINAL'."
        run: git commit -S -m "Create the packages of version '$VERSIONFINAL'."
        env:
          GITHUB_TOKEN: ${{ secrets.OSLASH_BOT_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.USER_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.USER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.USER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.USER_EMAIL }}

      - name: git push
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.OSLASH_BOT_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.USER_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.USER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.USER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.USER_EMAIL }}
