# Run test of the framework.
name: "[PRO][CREATE][WEB]"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  
jobs:
  Create_Web:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
          
      - name: Generate web
        run: .\\.tools\\doxygen\\doxygen.exe .\\.tools\\doxygen\\web_config

      - name: git config user.name github-actions
        run: git config user.name github-actions

      - name: git config user.email github-actions@github.com
        run: git config user.email github-actions@github.com

      - name: git config core.autocrlf false
        run: git config core.autocrlf false

      - name:  git add .
        run:  git add .

      - name: commit
        run: git commit -m "docs: create automatic web."

      - name:  git push
        run:  git push 