# Run test of the framework.
name: "[PRO][TEST][WINDOWS]"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  Test:
  
    name: WINDOWS-LATEST
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      
      - name: Dotnet test
        run: dotnet test alis.sln
