name: "[PRO][CHANGELOG]"

on:
  push:
    branches: [ master ]
    paths:
      - '**Directory.Build.props'
  
  pull_request:
    branches: [ master ]
    paths:
      - '**Directory.Build.props'

jobs:
  #
  # CREATE PACKAGES
  #
  
  Create_Packages:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Define file name to update version
        run: echo "FILENAME=$(echo './Directory.Build.props')" >> $GITHUB_ENV

      - name: Print the file name to update version
        run: echo $FILENAME

      - name: Get the current version
        run: echo "VERSION=$(grep -Eo '[0-9]\.[0-9]+.[0-9]+' ${{ env.FILENAME }} )" >> $GITHUB_ENV

      - name: Print the current version
        run: echo $VERSION

      - name: Update CHANGELOG
        id: changelog
        uses: Requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: "v'${{ env.VERSION }}'"
          writeToFile: true
          excludeTypes: chore, perf

      - name: create a file to save the log
        run: date > ./.publish/generated.txt

      - name: git config user.name github-actions
        run: git config user.name github-actions

      - name: git config user.email github-actions@github.com
        run: git config user.email github-actions@github.com

      - name: git config core.autocrlf false
        run: git config core.autocrlf false

      - name: git add .
        run: git add .

      - name: git commit -m "Update changelog '${{ env.VERSION }}'."
        run: git commit -m "Update changelog '${{ env.VERSION }}'."

      - name: git push
        run: git push
