name: "[PRO][DEPENDA][BOT]"

on:
  schedule:
    - cron: '30 1 * * *'
version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
