# Discover vulnerabilities of code.
name: "Discover_Vulnerabilities"

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  job1: 
    name: Testing Vulnerabilities
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Cache_Ubuntu_Code
        id: cache-ubuntu-code
        uses: actions/cache@v2
        with:
          path: temp-ubuntu-code
          key: ${{ runner.os }}-ubuntu-code

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
