name: Publish Nugets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Nugets:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Publish Alis.Core Nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH:  ./Core/Core.csproj
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
        NUGET_KEY: ${{secrets.NUGET}}
        
    - name: Publish Alis.Core-SFML Nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH:  ./Core-SFML/Core-SFML.csproj
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
        NUGET_KEY: ${{secrets.NUGET}}
        
    - name: Publish Alis.Tools Nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH:  ./Tools/Tools.csproj
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
        NUGET_KEY: ${{secrets.NUGET}}
